check – Fortran-lang/stdlib
check Subroutine
experimental
14 statements
Source File
public subroutine check(condition, msg, code, warn)
Checks the value of a logical condition (Specification)
Behavior
If condition == .false. and:
No other arguments are provided, it stops the program with the default message and exit code 1;
msg is provided, it prints the value of msg;
code is provided, it stops the program with the given exit code;
warn is provided and .true., it doesn't stop the program and prints the message.
Examples
If a /= 5, stops the program with exit code 1 and prints Check failed.
  call check(a == 5)
As above, but prints a == 5 failed.
  call check(a == 5, msg='a == 5 failed.')
As above, but doesn't stop the program.
  call check(a == 5, msg='a == 5 failed.', warn=.true.)
As example #2, but stops the program with exit code 77
  call check(a == 5, msg='a == 5 failed.', code=77)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: condition
character, intent(in), optional :: msg
integer, intent(in), optional :: code
logical, intent(in), optional :: warn
Calls
Called by
Contents
None
Call graph
check calls optval, error_stop
test_insert_at_string_1 calls check, compare_list
test_uni_pdf_iint32 calls check
test_expon_pdf_rdp calls check
test_expon_pdf_csp calls check
test_expon_rvs_rdp calls check
test_nor_cdf_rsp calls check
test_nor_rvs_rsp calls check
test_nor_rvs_cdp calls check
test_uni_cdf_iint8 calls check
test_sp calls check
test_exponential_random_generator calls check
test_expon_cdf_cdp calls check
test_expon_rvs_csp calls check
test_nor_cdf_cdp calls check
test_expon_cdf_rsp calls check
test_nor_rvs_csp calls check
test_expon_pdf_rsp calls check
test_nor_pdf_cdp calls check
test_nor_pdf_rsp calls check
test_expon_rvs_rsp calls check
test_uni_rvs_0 calls check
test_uni_pdf_iint16 calls check
test_uni_rvs_iint16 calls check
test_csp calls check
test_int64 calls check
test_always_fail calls check
test_nor_rvs_rdp calls check
test_uni_rvs_iint32 calls check
test_nor_cdf_csp calls check
test_uni_rvs_csp calls check
test_normal_random_generator calls check
test_constructor calls check
test_uni_cdf_csp calls check
compare_list calls check
test_uni_cdf_rdp calls check
test_uni_rvs_cdp calls check
test_uni_rvs_iint64 calls check
test_nor_pdf_csp calls check
test_uni_rvs_iint8 calls check
test_dp calls check
test_uni_pdf_cdp calls check
test_uni_cdf_rsp calls check
test_uni_cdf_cdp calls check
test_uni_pdf_csp calls check
test_expon_rvs_cdp calls check
test_nor_pdf_rdp calls check
test_append_prepend_array calls check, compare_list
test_cdp calls check
test_shuffle calls check
test_expon_cdf_csp calls check
test_uni_pdf_iint8 calls check
test_expon_pdf_cdp calls check
test_uni_pdf_rsp calls check
test_always_skip calls check
test_insert_at_string_2 calls check, compare_list
test_uni_rvs_rsp calls check
test_insert_at_string_3 calls check, compare_list
test_nor_cdf_rdp calls check
test_uni_cdf_iint32 calls check
test_int32 calls check
test_uni_cdf_iint16 calls check
test_append_prepend_string calls check, compare_list
test_uni_pdf_rdp calls check
test_uni_rvs_rdp calls check
test_append_prepend_list calls check, compare_list
test_uni_cdf_iint64 calls check
test_uni_pdf_iint64 calls check
test_expon_cdf_rdp calls check
test_distribution_uniform calls test_uni_pdf_iint32, test_uni_cdf_iint8, test_uni_rvs_0, test_uni_pdf_iint16, test_uni_rvs_iint16, test_uni_rvs_iint32, test_uni_rvs_csp, test_uni_cdf_csp, test_uni_cdf_rdp, test_uni_rvs_cdp, test_uni_rvs_iint64, test_uni_rvs_iint8, test_uni_pdf_cdp, test_uni_cdf_rsp, test_uni_cdf_cdp, test_uni_pdf_csp, test_shuffle, test_uni_pdf_iint8, test_uni_pdf_rsp, test_uni_rvs_rsp, test_uni_cdf_iint32, test_uni_cdf_iint16, test_uni_pdf_rdp, test_uni_rvs_rdp, test_uni_cdf_iint64, test_uni_pdf_iint64
test_cov calls test_sp, test_csp, test_int64, test_dp, test_cdp, test_int32
test_corr calls test_int64, test_dp, test_sp, test_cdp, test_csp, test_int32
test_insert_at_list calls compare_list
tester calls test_insert_at_string_1, test_constructor, test_insert_at_string_2, test_insert_at_string_3, test_insert_at_list, test_insert_at_array, test_append_prepend_array, test_append_prepend_string, test_append_prepend_list
test_insert_at_array calls compare_list
test_distribution_expon calls test_expon_pdf_rdp, test_expon_pdf_csp, test_expon_rvs_rdp, test_exponential_random_generator, test_expon_cdf_cdp, test_expon_rvs_csp, test_expon_cdf_rsp, test_expon_pdf_rsp, test_expon_rvs_rsp, test_expon_rvs_cdp, test_expon_cdf_csp, test_expon_pdf_cdp, test_expon_cdf_rdp
test_distribution_normal calls test_nor_cdf_rsp, test_nor_rvs_rsp, test_nor_rvs_cdp, test_nor_cdf_cdp, test_nor_rvs_csp, test_nor_pdf_cdp, test_nor_pdf_rsp, test_nor_rvs_rdp, test_nor_cdf_csp, test_normal_random_generator, test_nor_pdf_csp, test_nor_pdf_rdp, test_nor_cdf_rdp