check_slicer – Fortran-lang/stdlib
check_slicer Subroutine
26 statements
Source File
public subroutine check_slicer(error, string, first, last, stride)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
character(len=*), intent(in) :: string
integer, intent(in), optional :: first
integer, intent(in), optional :: last
integer, intent(in), optional :: stride
Calls
Called by
Contents
Variables
actual expected message stat
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: actual
character(len=:), public, allocatable :: expected
character(len=:), public, allocatable :: message
logical, public :: stat
Call graph
check_slicer calls slice, to_string, check, reference_slice
reference_slice calls string_to_carray, carray_to_string, optval
test_slice_gen calls check_slicer