check_formatter – Fortran-lang/stdlib
check_formatter Subroutine
18 statements
Source File
public subroutine check_formatter(error, actual, expected, description, partial)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
character(len=*), intent(in) :: actual
character(len=*), intent(in) :: expected
character(len=*), intent(in) :: description
logical, intent(in), optional :: partial
Calls
Called by
Contents
Variables
msg stat
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: msg
logical, public :: stat
Call graph
check_formatter calls starts_with, optval, check
test_to_string_logical calls check_formatter
test_to_string_real calls check_formatter
test_to_string_integer calls check_formatter
test_to_string_complex calls check_formatter