compare_list – Fortran-lang/stdlib
compare_list Subroutine
11 statements
Source File
public subroutine compare_list(list, first, last, call_number)
Arguments
Type Intent Optional Attributes Name
type(stringlist_type), intent(in) :: list
integer, intent(in) :: first
integer, intent(in) :: last
integer, intent(in) :: call_number
Calls
Called by
Contents
Variables
i j
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
Call graph
compare_list calls bidx, fidx, to_string, check
check calls error_stop, optval
test_append_prepend_list calls compare_list
test_append_prepend_array calls compare_list
test_append_prepend_string calls compare_list
tester calls test_append_prepend_list, test_append_prepend_array, test_append_prepend_string