compare_list – Fortran-lang/stdlib
compare_list Subroutine
11 statements
Source File
public subroutine compare_list(list, first, last, call_number)
Arguments
Type Intent Optional Attributes Name
type(stringlist_type), intent(in) :: list
integer, intent(in) :: first
integer, intent(in) :: last
integer, intent(in) :: call_number
Calls
Called by
Contents
Variables
i j
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
Call graph
compare_list calls fidx, to_string, bidx, check
check calls optval, error_stop
test_insert_at_list calls compare_list
test_insert_at_string_1 calls compare_list
test_insert_at_string_2 calls compare_list
test_insert_at_string_3 calls compare_list
test_insert_at_array calls compare_list
tester calls test_insert_at_list, test_insert_at_string_1, test_insert_at_string_2, test_insert_at_string_3, test_insert_at_array