cov_mask_2_iint8_dp – Fortran-lang/stdlib
cov_mask_2_iint8_dp Module Function
35 statements
Source File
function cov_mask_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
centeri_ centerj_ i j mask_ n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: centeri_(merge(size(x,2),size(x,1),mask=1
real(kind=dp), public :: centerj_(merge(size(x,2),size(x,1),mask=1
integer, public :: i
integer, public :: j
logical, public :: mask_(merge(size(x,2),size(x,1),mask=1
integer, public :: n
Call graph
cov_mask_2_iint8_dp calls error_stop, mean, optval
error_stop calls error_stop
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character