cov_1_iint8_dp – Fortran-lang/stdlib
cov_1_iint8_dp Module Function
12 statements
Source File
function cov_1_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
None
Call graph
cov_1_iint8_dp calls var, optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp