cov_2_cdp_cdp – Fortran-lang/stdlib
cov_2_cdp_cdp Module Function
30 statements
Source File
function cov_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
center i mean_
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public :: center(size(x,1),size(x,2))
integer, public :: i
complex(kind=dp), public :: mean_(merge(size(x,1),size(x,2),mask=1
Call graph
cov_2_cdp_cdp calls optval, mean, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop