cov_mask_2_cdp_cdp – Fortran-lang/stdlib
cov_mask_2_cdp_cdp Module Function
35 statements
Source File
function cov_mask_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
centeri_ centerj_ i j mask_ n
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public :: centeri_(merge(size(x,2),size(x,1),mask=1
complex(kind=dp), public :: centerj_(merge(size(x,2),size(x,1),mask=1
integer, public :: i
integer, public :: j
logical, public :: mask_(merge(size(x,2),size(x,1),mask=1
integer, public :: n
Call graph
cov_mask_2_cdp_cdp calls error_stop, optval, mean
error_stop calls error_stop
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32