cov_1_iint32_dp – Fortran-lang/stdlib
cov_1_iint32_dp Module Function
12 statements
Source File
function cov_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
None
Call graph
cov_1_iint32_dp calls optval, var
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64