cov_mask_2_iint32_dp – Fortran-lang/stdlib
cov_mask_2_iint32_dp Module Function
37 statements
Source File
function cov_mask_2_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
center i j mean_ n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: center(size(x,1),size(x,2))
integer, public :: i
integer, public :: j
real(kind=dp), public :: mean_(merge(size(x,1),size(x,2),mask=1
integer, public :: n
Call graph
cov_mask_2_iint32_dp calls optval, mean, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop