cov_2_rqp_rqp – Fortran-lang/stdlib
cov_2_rqp_rqp Module Function
30 statements
Source File
function cov_2_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
center i mean_
Variables
Type Visibility Attributes Name Initial
real(kind=qp), public :: center(size(x,1),size(x,2))
integer, public :: i
real(kind=qp), public :: mean_(merge(size(x,1),size(x,2),mask=1
Call graph
cov_2_rqp_rqp calls error_stop, mean, optval
error_stop calls error_stop
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character