cov_mask_1_iint64_dp – Fortran-lang/stdlib
cov_mask_1_iint64_dp Module Function
8 statements
Source File
function cov_mask_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
None
Call graph
cov_mask_1_iint64_dp calls var, optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp