cov_mask_2_iint16_dp – Fortran-lang/stdlib
cov_mask_2_iint16_dp Module Function
37 statements
Source File
function cov_mask_2_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
center i j mean_ n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: center(size(x,1),size(x,2))
integer, public :: i
integer, public :: j
real(kind=dp), public :: mean_(merge(size(x,1),size(x,2),mask=1
integer, public :: n
Call graph
cov_mask_2_iint16_dp calls error_stop, mean, optval
error_stop calls error_stop
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp