cov_1_cdp_cdp – Fortran-lang/stdlib
cov_1_cdp_cdp Module Function
12 statements
Source File
function cov_1_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
None
Call graph
cov_1_cdp_cdp calls var, optval
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character