cov_mask_1_csp_csp – Fortran-lang/stdlib
cov_mask_1_csp_csp Module Function
8 statements
Source File
function cov_mask_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
Calls
Contents
None
Call graph
cov_mask_1_csp_csp calls var, optval
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp