cov_2_cqp_cqp – Fortran-lang/stdlib
cov_2_cqp_cqp Module Function
30 statements
Source File
function cov_2_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
center i mean_
Variables
Type Visibility Attributes Name Initial
complex(kind=qp), public :: center(size(x,1),size(x,2))
integer, public :: i
complex(kind=qp), public :: mean_(merge(size(x,1),size(x,2),mask=1
Call graph
cov_2_cqp_cqp calls mean, optval, error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp
error_stop calls error_stop