cov_1_csp_csp – Fortran-lang/stdlib
cov_1_csp_csp Module Function
12 statements
Source File
function cov_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
Calls
Contents
None
Call graph
cov_1_csp_csp calls optval, var
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32