eye – Fortran-lang/stdlib
eye Function
experimental
13 statements
Source File
public pure function eye(dim1, dim2) result(result)
Constructs the identity matrix. (Specification)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dim1
integer, intent(in), optional :: dim2
Return Value integer(kind=int8),allocatable,(:,:)
Calls
Called by
Contents
None
Call graph
eye calls optval
test_diag_int16 calls eye
test_diag_int8 calls eye
test_eye calls eye