is_alphanum – Fortran-lang/stdlib
is_alphanum Function
4 statements
Source File
public pure function is_alphanum(c)
Checks whether c is a letter or a number (0 .. 9, a .. z, A .. Z).
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
The character to test.
Return Value logical
Called by
Contents
None
Call graph
to_sentence calls is_alphanum
is_punctuation calls is_alphanum
to_title calls is_alphanum