mean_4_cdp_cdp – Fortran-lang/stdlib
mean_4_cdp_cdp Module Function
15 statements
Source File
function mean_4_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
mean_4_cdp_cdp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp