mean_3_iint32_dp – Fortran-lang/stdlib
mean_3_iint32_dp Module Function
15 statements
Source File
function mean_3_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
mean_3_iint32_dp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character