mean_all_3_csp_csp – Fortran-lang/stdlib
mean_all_3_csp_csp Module Function
10 statements
Source File
function mean_all_3_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
Calls
Contents
None
Call graph
mean_all_3_csp_csp calls optval
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character