mean_all_3_cqp_cqp – Fortran-lang/stdlib
mean_all_3_cqp_cqp Module Function
10 statements
Source File
function mean_all_3_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
Calls
Contents
None
Call graph
mean_all_3_cqp_cqp calls optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp