mean_3_rdp_rdp – Fortran-lang/stdlib
mean_3_rdp_rdp Module Function
15 statements
Source File
function mean_3_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
mean_3_rdp_rdp calls error_stop, optval
error_stop calls error_stop
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32