mean_1_csp_csp – Fortran-lang/stdlib
mean_1_csp_csp Module Function
15 statements
Source File
function mean_1_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
Calls
Contents
None
Call graph
mean_1_csp_csp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp