mean_all_4_rsp_rsp – Fortran-lang/stdlib
mean_all_4_rsp_rsp Module Function
10 statements
Source File
function mean_all_4_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=sp)
Calls
Contents
None
Call graph
mean_all_4_rsp_rsp calls optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp