mean_all_2_csp_csp – Fortran-lang/stdlib
mean_all_2_csp_csp Module Function
10 statements
Source File
function mean_all_2_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
Calls
Contents
None
Call graph
mean_all_2_csp_csp calls optval
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32