mean_all_1_iint8_dp – Fortran-lang/stdlib
mean_all_1_iint8_dp Module Function
10 statements
Source File
function mean_all_1_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
Calls
Contents
None
Call graph
mean_all_1_iint8_dp calls optval
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp