mixed_check2 – Fortran-lang/stdlib
mixed_check2 Subroutine
11 statements
Source File
public subroutine mixed_check2(error, chr1, chr2, checker)
Run the actual checker with one string type generated by the custom constructor and the other by assignment
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
character(len=*), intent(in) :: chr1
character(len=*), intent(in) :: chr2
procedure(check2_interface) :: checker
Called by
Contents
Variables
str1 str2
Variables
Type Visibility Attributes Name Initial
type(string_type), public :: str1
type(string_type), public :: str2
Call graph
check2 calls mixed_check2
test_lle calls check2
test_llt calls check2
test_index calls check2
test_lge calls check2
test_lgt calls check2
test_verify calls check2
test_scan calls check2