moment_scalar_3_csp_csp – Fortran-lang/stdlib
moment_scalar_3_csp_csp Module Function
17 statements
Source File
function moment_scalar_3_csp_csp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=sp), intent(in) :: center
logical, intent(in), optional :: mask
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
moment_scalar_3_csp_csp calls error_stop, optval
error_stop calls error_stop
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32