moment_4_iint32_dp – Fortran-lang/stdlib
moment_4_iint32_dp Module Function
70 statements
Source File
function moment_4_iint32_dp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
real(kind=dp), intent(in), optional :: center(merge(size(x,1),size(x,2),mask=1
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public, allocatable :: mean_(:,:,:)
real(kind=dp), public :: n
Call graph
moment_4_iint32_dp calls optval, mean, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop