moment_3_cqp_cqp – Fortran-lang/stdlib
moment_3_cqp_cqp Module Function
58 statements
Source File
function moment_3_cqp_cqp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=qp), intent(in), optional :: center(merge(size(x,1),size(x,2),mask=1
logical, intent(in), optional :: mask
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=qp), public, allocatable :: mean_(:,:)
real(kind=qp), public :: n
Call graph
moment_3_cqp_cqp calls mean, optval, error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp
error_stop calls error_stop