moment_2_csp_csp – Fortran-lang/stdlib
moment_2_csp_csp Module Function
46 statements
Source File
function moment_2_csp_csp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=sp), intent(in), optional :: center(merge(size(x,1),size(x,2),mask=1
logical, intent(in), optional :: mask
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=sp), public, allocatable :: mean_(:)
real(kind=sp), public :: n
Call graph
moment_2_csp_csp calls error_stop, mean, optval
error_stop calls error_stop
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character