moment_scalar_4_iint64_dp – Fortran-lang/stdlib
moment_scalar_4_iint64_dp Module Function
17 statements
Source File
function moment_scalar_4_iint64_dp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
real(kind=dp), intent(in) :: center
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
moment_scalar_4_iint64_dp calls error_stop, optval
error_stop calls error_stop
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp