moment_1_cdp_cdp – Fortran-lang/stdlib
moment_1_cdp_cdp Module Function
34 statements
Source File
function moment_1_cdp_cdp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=dp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=dp), public, allocatable :: mean_
real(kind=dp), public :: n
Call graph
moment_1_cdp_cdp calls error_stop, optval, mean
error_stop calls error_stop
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32