moment_all_3_csp_csp – Fortran-lang/stdlib
moment_all_3_csp_csp Module Function
18 statements
Source File
function moment_all_3_csp_csp(x, order, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: order
complex(kind=sp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
Calls
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public :: n
Call graph
moment_all_3_csp_csp calls optval, mean
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64