moment_scalar_2_cqp_cqp – Fortran-lang/stdlib
moment_scalar_2_cqp_cqp Module Function
17 statements
Source File
function moment_scalar_2_cqp_cqp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=qp), intent(in) :: center
logical, intent(in), optional :: mask
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
None
Call graph
moment_scalar_2_cqp_cqp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp