moment_1_cqp_cqp – Fortran-lang/stdlib
moment_1_cqp_cqp Module Function
34 statements
Source File
function moment_1_cqp_cqp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=qp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=qp), public, allocatable :: mean_
real(kind=qp), public :: n
Call graph
moment_1_cqp_cqp calls error_stop, optval, mean
error_stop calls error_stop
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp