moment_all_4_cdp_cdp – Fortran-lang/stdlib
moment_all_4_cdp_cdp Module Function
18 statements
Source File
function moment_all_4_cdp_cdp(x, order, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: order
complex(kind=dp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
Calls
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: n
Call graph
moment_all_4_cdp_cdp calls optval, mean
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32