moment_all_2_rqp_rqp – Fortran-lang/stdlib
moment_all_2_rqp_rqp Module Function
18 statements
Source File
function moment_all_2_rqp_rqp(x, order, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: order
real(kind=qp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value real(kind=qp)
Calls
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
real(kind=qp), public :: n
Call graph
moment_all_2_rqp_rqp calls mean, optval
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character