moment_all_4_iint32_dp – Fortran-lang/stdlib
moment_all_4_iint32_dp Module Function
18 statements
Source File
function moment_all_4_iint32_dp(x, order, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: order
real(kind=dp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value real(kind=dp)
Calls
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: n
Call graph
moment_all_4_iint32_dp calls mean, optval
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp