moment_all_3_rdp_rdp – Fortran-lang/stdlib
moment_all_3_rdp_rdp Module Function
18 statements
Source File
function moment_all_3_rdp_rdp(x, order, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: order
real(kind=dp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value real(kind=dp)
Calls
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: n
Call graph
moment_all_3_rdp_rdp calls optval, mean
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp