moment_3_cdp_cdp – Fortran-lang/stdlib
moment_3_cdp_cdp Module Function
58 statements
Source File
function moment_3_cdp_cdp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
complex(kind=dp), intent(in), optional :: center(merge(size(x,1),size(x,2),mask=1
logical, intent(in), optional :: mask
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=dp), public, allocatable :: mean_(:,:)
real(kind=dp), public :: n
Call graph
moment_3_cdp_cdp calls optval, mean, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop