moment_1_rdp_rdp – Fortran-lang/stdlib
moment_1_rdp_rdp Module Function
34 statements
Source File
function moment_1_rdp_rdp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: order
integer, intent(in) :: dim
real(kind=dp), intent(in), optional :: center
logical, intent(in), optional :: mask
Return Value real(kind=dp)
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public, allocatable :: mean_
real(kind=dp), public :: n
Call graph
moment_1_rdp_rdp calls mean, optval, error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp
error_stop calls error_stop