moment_mask_4_iint64_dp – Fortran-lang/stdlib
moment_mask_4_iint64_dp Module Function
66 statements
Source File
function moment_mask_4_iint64_dp(x, order, dim, center, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: order
integer, intent(in) :: dim
real(kind=dp), intent(in), optional :: center(merge(size(x,1),size(x,2),mask=1
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean_ n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public, allocatable :: mean_(:,:,:)
real(kind=dp), public :: n(merge(size(x,1),size(x,2),mask=1
Call graph
moment_mask_4_iint64_dp calls mean, error_stop
error_stop calls error_stop