number_of_rows_numeric – Fortran-lang/stdlib
number_of_rows_numeric Function
22 statements
Source File
private function number_of_rows_numeric(s) result(nrows)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: s
Return Value integer
Called by
Contents
Variables
ios r z
Source Code
number_of_rows_numeric
Variables
Type Visibility Attributes Name Initial
integer, public :: ios
real, public :: r
complex, public :: z
Source Code
  integer function number_of_rows_numeric(s) result(nrows)
    ! determine number or rows
    integer,intent(in)::s
    integer :: ios
    real :: r
    complex :: z
    rewind(s)
    nrows = 0
    do
      read(s, *, iostat=ios) r
      if (ios /= 0) exit
      nrows = nrows + 1
    end do
    rewind(s)
    ! If there are no rows of real numbers, it may be that they are complex
    if( nrows == 0) then
      do
        read(s, *, iostat=ios) z
        if (ios /= 0) exit
        nrows = nrows + 1
      end do
      rewind(s)
    end if
  end function number_of_rows_numeric
Call graph
loadtxt_cdp calls number_of_rows_numeric
loadtxt_cqp calls number_of_rows_numeric
loadtxt_iint16 calls number_of_rows_numeric
loadtxt_iint32 calls number_of_rows_numeric
loadtxt_iint8 calls number_of_rows_numeric
loadtxt_rqp calls number_of_rows_numeric
loadtxt_rdp calls number_of_rows_numeric
loadtxt_rsp calls number_of_rows_numeric
loadtxt_iint64 calls number_of_rows_numeric
loadtxt_csp calls number_of_rows_numeric
loadtxt calls loadtxt_cdp, loadtxt_cqp, loadtxt_iint16, loadtxt_iint32, loadtxt_iint8, loadtxt_rqp, loadtxt_rdp, loadtxt_rsp, loadtxt_iint64, loadtxt_csp