number_of_columns – Fortran-lang/stdlib
number_of_columns Function
16 statements
Source File
private function number_of_columns(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: s
Return Value integer
Calls
Called by
Contents
Variables
c ios lastblank
Source Code
number_of_columns
Variables
Type Visibility Attributes Name Initial
character, public :: c
integer, public :: ios
logical, public :: lastblank
Source Code
  integer function number_of_columns(s)
    ! determine number of columns
    integer,intent(in) :: s
    integer :: ios
    character :: c
    logical :: lastblank
    rewind(s)
    number_of_columns = 0
    lastblank = .true.
    do
      read(s, '(a)', advance='no', iostat=ios) c
      if (ios /= 0) exit
      if (lastblank .and. .not. is_blank(c)) number_of_columns = number_of_columns + 1
      lastblank = is_blank(c)
    end do
    rewind(s)
  end function number_of_columns
Call graph
number_of_columns calls is_blank
loadtxt_iint64 calls number_of_columns
loadtxt_cqp calls number_of_columns
loadtxt_rsp calls number_of_columns
loadtxt_iint8 calls number_of_columns
loadtxt_csp calls number_of_columns
loadtxt_iint16 calls number_of_columns
loadtxt_iint32 calls number_of_columns
loadtxt_rqp calls number_of_columns
loadtxt_cdp calls number_of_columns
loadtxt_rdp calls number_of_columns
loadtxt calls loadtxt_iint64, loadtxt_cqp, loadtxt_rsp, loadtxt_iint8, loadtxt_csp, loadtxt_iint16, loadtxt_iint32, loadtxt_rqp, loadtxt_cdp, loadtxt_rdp