open – Fortran-lang/stdlib
open Function
58 statements
Source File
public function open(filename, mode, iostat) result(u)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in), optional :: mode
integer, intent(out), optional :: iostat
Return Value integer
Calls
Contents
Variables
access_ action_ form_ mode_ position_ status_
Source Code
open
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: access_
character(len=:), public, allocatable :: action_
character(len=:), public, allocatable :: form_
character(len=3), public :: mode_
character(len=:), public, allocatable :: position_
character(len=:), public, allocatable :: status_
Source Code
  integer function open(filename, mode, iostat) result(u)
    ! Open a file
    !
    ! To open a file to read:
    !
    ! u = open("somefile.txt")        # The default `mode` is "rt"
    ! u = open("somefile.txt", "r")
    !
    ! To open a file to write:
    !
    ! u = open("somefile.txt", "w")
    ! To append to the end of the file if it exists:
    !
    ! u = open("somefile.txt", "a")
    character(*), intent(in) :: filename
    character(*), intent(in), optional :: mode
    integer, intent(out), optional :: iostat
    character(3) :: mode_
    character(:),allocatable :: action_, position_, status_, access_, form_
    mode_ = parse_mode(optval(mode, ""))
    select case (mode_(1:2))
    case('r')
      action_='read'
      position_='asis'
      status_='old'
    case('w')
      action_='write'
      position_='asis'
      status_='replace'
    case('a')
      action_='write'
      position_='append'
      status_='old'
    case('x')
      action_='write'
      position_='asis'
      status_='new'
    case('r+')
      action_='readwrite'
      position_='asis'
      status_='old'
    case('w+')
      action_='readwrite'
      position_='asis'
      status_='replace'
    case('a+')
      action_='readwrite'
      position_='append'
      status_='old'
    case('x+')
      action_='readwrite'
      position_='asis'
      status_='new'
    case default
      call error_stop("Unsupported mode: "//mode_(1:2))
    end select
    select case (mode_(3:3))
    case('t')
      form_='formatted'
    case('b')
      form_='unformatted'
    case default
      call error_stop("Unsupported mode: "//mode_(3:3))
    end select
    access_ = 'stream'
    if (present(iostat)) then
      open(newunit=u, file=filename, &
          action = action_, position = position_, status = status_, &
          access = access_, form = form_, &
          iostat = iostat)
    else
      open(newunit=u, file=filename, &
          action = action_, position = position_, status = status_, &
          access = access_, form = form_)
    end if
  end function open
Call graph
open calls optval, parse_mode
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp