test_uni_rvs_cdp – Fortran-lang/stdlib
test_uni_rvs_cdp Subroutine
19 statements
Source File
subroutine test_uni_rvs_cdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k loc n res scale seed
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public, parameter :: ans(15) = [(0.457413314269374593479255963757168502_dp, 0.183665049332483204524990583195176441_dp), (0.887956215288546402142344504682114348_dp, 0.442960654493795069619466175936395302_dp), (0.475367828271493930714086673106066883_dp, 0.170218713071472432796227280960010830_dp), (0.441669140746526411867023398372111842_dp, 0.918695946946929575815943280758801848_dp), (0.148022801700699729865462472844228614_dp, 0.691296364925570783199759716808330268_dp), (-6.623624698909258423640267210430465639E-0002_dp, 0.560638316852891907537959070850774879_dp), (-0.450830023070757909819938902273861459_dp, 0.917954692926131299302028310194145888_dp), (-0.166943359095192145336028488600277342_dp, 1.05997401970850635422038976685144007_dp), (-0.429652190199228276035192664039641386_dp, 0.523558274341032421628217008446881664_dp), (0.427181091476823815433760955784237012_dp, 1.34628934976074521312483511792379431_dp), (-0.343281426018765739582860874179459643_dp, 1.15357331316264255516301773241139017_dp), (-0.127590074749816595467422075671493076_dp, 1.06891199479835175001340985545539297_dp), (0.262287586904722758163188700564205647_dp, 1.29508919831907332032017166056903079_dp), (-0.192677407376582732201342196276527829_dp, 1.32794925614337933073016984053538181_dp), (-0.264742129752461530234342035328154452_dp, 1.01282963412172621886497836385387927_dp)]
integer, public :: get
integer, public :: i
integer, public :: k
complex(kind=dp), public :: loc
integer, public :: n
complex(kind=dp), public :: res(15)
complex(kind=dp), public :: scale
integer, public :: seed
Call graph
test_uni_rvs_cdp calls uni_rvs, check
check calls error_stop, optval
test_distribution_uniform calls test_uni_rvs_cdp