test_append_prepend_string – Fortran-lang/stdlib
test_append_prepend_string Subroutine
28 statements
Source File
public subroutine test_append_prepend_string()
Arguments
None
Calls
Called by
Contents
Variables
first i last reference_list string work_list
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: first = -100
integer, public :: i
integer, public, parameter :: last = 100
type(stringlist_type), public :: reference_list
character(len=:), public, allocatable :: string
type(stringlist_type), public :: work_list
Call graph
test_append_prepend_string calls to_string, check, compare_list, fidx, bidx
check calls error_stop, optval
compare_list calls to_string, check, fidx, bidx
tester calls test_append_prepend_string