test_gauss_5 – Fortran-lang/stdlib
test_gauss_5 Subroutine
22 statements
Source File
public subroutine test_gauss_5(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
i
Variables
Type Visibility Attributes Name Initial
integer, public :: i
Call graph
test_gauss_5 calls w, check, x, gauss_legendre, wref, xref