test_optval_rdp – Fortran-lang/stdlib
test_optval_rdp Subroutine
6 statements
Source File
public subroutine test_optval_rdp(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
None
Call graph
test_optval_rdp calls foo_dp, check
foo_dp calls optval