test_expon_rvs_cdp – Fortran-lang/stdlib
test_expon_rvs_cdp Subroutine
16 statements
Source File
subroutine test_expon_rvs_cdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k n res scale seed
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public, parameter :: ans(10) = [(1.30645817419194517786503898345732266_dp, 0.158701181060322271676454874977935106_dp), (0.289117517640543687994027420375329869_dp, 1.54345454641418945184428733997405138_dp), (0.238175330520730461308127295134389521_dp, 0.616098062265619464192503493485184250_dp), (4.21923061197273582426500329997257485_dp, 0.428206128453374382877209077728016710_dp), (1.73982581934785075970596933205212874_dp, 0.466889832630805233184044202341912994_dp), (2.22649889847873832288931745486999202_dp, 0.879109337848515628785697537331053851_dp), (8.76802198822945553859296653951917464_dp, 0.200128045239398311139211728004738688_dp), (0.694821947760945587572020290930855262_dp, 0.101964167346166995492113143812345625_dp), (0.141476585024528208770330398432893829_dp, 3.989655879458742013468417133900891716E-0002_dp), (2.10676792861163792685325850990401309_dp, 0.249356813451327473065187125310051027_dp)]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
integer, public :: n
complex(kind=dp), public :: res(10)
complex(kind=dp), public :: scale
integer, public :: seed
Call graph
test_expon_rvs_cdp calls rvs_exp, check
check calls optval, error_stop
test_distribution_expon calls test_expon_rvs_cdp