test_string_sort_index – Fortran-lang/stdlib
test_string_sort_index Subroutine
27 statements
Source File
public subroutine test_string_sort_index(a, a_name, ltest)
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: a(0:)
character, intent(in) :: a_name
logical, intent(out) :: ltest
Calls
Called by
Contents
Variables
i rate t0 t1 tdiff valid
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public :: i
real(kind=dp), public :: rate
integer(kind=int64), public :: t0
integer(kind=int64), public :: t1
integer(kind=int64), public :: tdiff
logical, public :: valid
Call graph
test_string_sort_index calls verify_string_sort, sort_index
test_string_sort_indexes calls test_string_sort_index