test_nor_rvs_csp – Fortran-lang/stdlib
test_nor_rvs_csp Subroutine
17 statements
Source File
subroutine test_nor_rvs_csp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k loc n res scale seed
Variables
Type Visibility Attributes Name Initial
complex(kind=sp), public, parameter :: ans(10) = [(2.12531029488530509574673033057479188_sp, 1.46507698734032082432676702410390135_sp), (1.08284164094813181722365413861552952_sp, 0.277168639672963013076412153168348595_sp), (1.41924946329521489696290359461272601_sp, 0.498445561155580918466512230224907398_sp), (1.72639126368764062036120776610914618_sp, 0.715802936564464420410303091557580046_sp), (1.98950590834134349860207180427096318_sp, 0.115721315405046931701349421928171068_sp), (-1.16929014824793620075382705181255005_sp, 0.250744737486995217246033007540972903_sp), (1.57160542831869509683428987045772374_sp, 0.638282596371312238581197107123443857_sp), (-1.36106107654239116833139178197598085_sp, 0.166259201494369124318950525776017457_sp), (1.13403096805387920698038328737311531_sp, 1.04232618148691447146347854868508875_sp), (-1.68220535920475811053620418533682823_sp, 1.63361446685040256898702182297711261_sp)]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
complex(kind=sp), public :: loc
integer, public :: n
complex(kind=sp), public :: res(10)
complex(kind=sp), public :: scale
integer, public :: seed
Call graph
test_nor_rvs_csp calls check, rvs_normal
check calls error_stop, optval
test_distribution_normal calls test_nor_rvs_csp