test_simps_weights_even_dp – Fortran-lang/stdlib
test_simps_weights_even_dp Subroutine
20 statements
Source File
public subroutine test_simps_weights_even_dp(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
ans even i n val w x y
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: ans
integer, public :: even
integer, public :: i
integer, public, parameter :: n = 16
real(kind=dp), public :: val
real(kind=dp), public, dimension(n) :: w
real(kind=dp), public, dimension(n) :: x
real(kind=dp), public, dimension(n) :: y
Call graph
test_simps_weights_even_dp calls simps_weights, simps, check