test_int_ord_sorts – Fortran-lang/stdlib
test_int_ord_sorts Subroutine
37 statements
Source File
public subroutine test_int_ord_sorts(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
d1 i ltest
Variables
Type Visibility Attributes Name Initial
integer, public, allocatable :: d1(:)
integer(kind=int64), public :: i
logical, public :: ltest
Call graph
test_int_ord_sorts calls check, test_int_ord_sort, ord_sort, verify_sort
test_int_ord_sort calls ord_sort, verify_sort, verify_reverse_sort