test_nor_pdf_rdp – Fortran-lang/stdlib
test_nor_pdf_rdp Subroutine
17 statements
Source File
subroutine test_nor_pdf_rdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k loc n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: ans(15) = [0.215050766989949083210785218076278553_dp, 0.215050766989949083210785218076278553_dp, 0.215050766989949083210785218076278553_dp, 0.200537626692880596839299818454439236_dp, 5.66161527403268434368575024104022496E-0002_dp, 0.238986957612021514867582359518579138_dp, 0.265935969411942911029638292783132425_dp, 0.262147558654079961109031890374902943_dp, 0.249866408914952245533320687656894701_dp, 3.98721117498705317877792757313696510E-0002_dp, 0.265902369803533466897906694845094995_dp, 0.161311603170650092038944290133124635_dp, 0.249177740354276111998717092437037695_dp, 0.237427217242213206474603807278971527_dp, 0.155696086384122017518186260628090478_dp]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
real(kind=dp), public :: loc
integer, public :: n
real(kind=dp), public :: res(3,5)
real(kind=dp), public :: scale
integer, public :: seed
real(kind=dp), public :: x1
real(kind=dp), public :: x2(3,4)
Call graph
test_nor_pdf_rdp calls rvs_normal, pdf_normal, check
check calls error_stop, optval
test_distribution_normal calls test_nor_pdf_rdp