test_expon_cdf_rdp – Fortran-lang/stdlib
test_expon_cdf_rdp Subroutine
16 statements
Source File
subroutine test_expon_cdf_rdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: ans(15) = [0.109257742653704886153815776449785051_dp, 0.109257742653704886153815776449785051_dp, 0.109257742653704886153815776449785051_dp, 0.717506371795765265795319089684216215_dp, 6.82471795435370961628021592837348251E-0002_dp, 0.158022297254037860379992220663140220_dp, 0.914579543576380160727189390750289231_dp, 0.735445094339121647068624074363021598_dp, 8.69845458684957375690771394578441361E-0002_dp, 0.491195342629961409581199224477971938_dp, 0.574283568793105916250099261345264380_dp, 0.312823040527767907760475800138803955_dp, 0.640029783598040153827956625977856239_dp, 2.16202116731629451897815202649346917E-0002_dp, 7.74788145547936974757767867581111655E-0002_dp]
integer, public :: get
integer, public :: i
integer, public :: n
real(kind=dp), public :: res(3,5)
real(kind=dp), public :: scale
integer, public :: seed
real(kind=dp), public :: x1
real(kind=dp), public :: x2(3,4)
Call graph
test_expon_cdf_rdp calls cdf_exp, rvs_exp, check
check calls error_stop, optval
test_distribution_expon calls test_expon_cdf_rdp