test_nor_rvs_cdp – Fortran-lang/stdlib
test_nor_rvs_cdp Subroutine
17 statements
Source File
subroutine test_nor_rvs_cdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k loc n res scale seed
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public, parameter :: ans(10) = [(2.12531029488530509574673033057479188_dp, 1.46507698734032082432676702410390135_dp), (1.08284164094813181722365413861552952_dp, 0.277168639672963013076412153168348595_dp), (1.41924946329521489696290359461272601_dp, 0.498445561155580918466512230224907398_dp), (1.72639126368764062036120776610914618_dp, 0.715802936564464420410303091557580046_dp), (1.98950590834134349860207180427096318_dp, 0.115721315405046931701349421928171068_dp), (-1.16929014824793620075382705181255005_dp, 0.250744737486995217246033007540972903_dp), (1.57160542831869509683428987045772374_dp, 0.638282596371312238581197107123443857_dp), (-1.36106107654239116833139178197598085_dp, 0.166259201494369124318950525776017457_dp), (1.13403096805387920698038328737311531_dp, 1.04232618148691447146347854868508875_dp), (-1.68220535920475811053620418533682823_dp, 1.63361446685040256898702182297711261_dp)]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
complex(kind=dp), public :: loc
integer, public :: n
complex(kind=dp), public :: res(10)
complex(kind=dp), public :: scale
integer, public :: seed
Call graph
test_nor_rvs_cdp calls check, rvs_normal
check calls optval, error_stop
test_distribution_normal calls test_nor_rvs_cdp