test_uni_cdf_rsp – Fortran-lang/stdlib
test_uni_cdf_rsp Subroutine
16 statements
Source File
subroutine test_uni_cdf_rsp()
Arguments
None
Calls
Called by
Contents
Variables
ans get loc res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public, parameter :: ans(15) = [0.170192944297557408050991512027394492_sp, 0.170192944297557408050991512027394492_sp, 0.170192944297557408050991512027394492_sp, 0.276106146274646191418611351764411665_sp, 0.754930097473875072466853453079238534_sp, 0.406620682573118008562573777453508228_sp, 0.187742819191801080247472555129206739_sp, 0.651605526090507591874256831943057477_sp, 0.934733949732104885121941606485052034_sp, 0.151271491851613287815681019310432021_sp, 0.987674522797719611766353864368284121_sp, 0.130533899463404684526679488953959662_sp, 0.106271905921876880229959283497009892_sp, 9.27578652240113182836367400341259781E-0002_sp, 0.203399426853420439709196898547816090_sp]
integer, public :: get
real(kind=sp), public :: loc
real(kind=sp), public :: res(3,5)
real(kind=sp), public :: scale
integer, public :: seed
real(kind=sp), public :: x1
real(kind=sp), public :: x2(3,4)
Call graph
test_uni_cdf_rsp calls uni_cdf, uni_rvs, check
check calls optval, error_stop
test_distribution_uniform calls test_uni_cdf_rsp