test_diff_real_sp – Fortran-lang/stdlib
test_diff_real_sp Subroutine
25 statements
Source File
public subroutine test_diff_real_sp(error)
rank-1 diff rank-2 diff size(B, dim) <= n
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Calls
Contents
Variables
A B x
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public :: A(1,3) = reshape([real(sp)::1, 3, 5], [1, 3])
real(kind=sp), public :: B(2) = [real(sp)::1, 2]
real(kind=sp), public :: x(6) = [real(sp)::0, 5, 15, 30, 50, 75]
Call graph
test_diff_real_sp calls diff, all_close, check