test_expon_rvs_rdp – Fortran-lang/stdlib
test_expon_rvs_rdp Subroutine
16 statements
Source File
subroutine test_expon_rvs_rdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k n res scale seed
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: ans(10) = [0.609680481289574416337018192280083895_dp, 0.137541023585612635452927558314210417_dp, 0.134921508232253721063879462841820585_dp, 1.33766060689229752493171569464417802_dp, 0.111148487576340881943792737729381770_dp, 0.533951653963536868966836361020492979_dp, 1.96897428558727671799033487332053483_dp, 0.371111977992924465160247867364281152_dp, 0.811918715695663687862785688290993341_dp, 0.404637854946697868759504975362991277_dp]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
integer, public :: n
real(kind=dp), public :: res(10)
real(kind=dp), public :: scale
integer, public :: seed
Call graph
test_expon_rvs_rdp calls rvs_exp, check
check calls optval, error_stop
test_distribution_expon calls test_expon_rvs_rdp