test_gauss_64 – Fortran-lang/stdlib
test_gauss_64 Subroutine
140 statements
Source File
public subroutine test_gauss_64(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
i
Variables
Type Visibility Attributes Name Initial
integer, public :: i
Call graph
test_gauss_64 calls check, wref, xref, x, w, gauss_legendre