test_uni_pdf_iint64 – Fortran-lang/stdlib
test_uni_pdf_iint64 Subroutine
16 statements
Source File
subroutine test_uni_pdf_iint64()
Arguments
None
Calls
Called by
Contents
Variables
ans get i loc res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real, public, parameter :: ans(15) = [(1.96078438E-02, i=1, 15)]
integer, public :: get
integer, public :: i
integer(kind=int64), public :: loc
real, public :: res(3,5)
integer(kind=int64), public :: scale
integer, public :: seed
integer(kind=int64), public :: x1
integer(kind=int64), public :: x2(3,4)
Call graph
test_uni_pdf_iint64 calls uni_pdf, uni_rvs, check
check calls error_stop, optval
test_distribution_uniform calls test_uni_pdf_iint64