test_nor_pdf_cdp – Fortran-lang/stdlib
test_nor_pdf_cdp Subroutine
17 statements
Source File
subroutine test_nor_pdf_cdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i k loc n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: ans(15) = [0.129377311291944176372137325120411497_dp, 0.129377311291944176372137325120411497_dp, 0.129377311291944176372137325120411497_dp, 4.05915662853246811934977653001971736E-0002_dp, 0.209143395418940756076861773161637924_dp, 2.98881041363874672676853084975547667E-0002_dp, 0.128679412679649127469385460133445161_dp, 0.177484732473055532384223611956177231_dp, 3.82205306942578982084957100753849738E-0002_dp, 7.09915714309796034515515428785324918E-0002_dp, 4.56126582912124629544443072483362352E-0002_dp, 6.57454133967021123696499056531595921E-0002_dp, 0.165161039915667041643464172210282279_dp, 3.86104822953520989775015755966798359E-0002_dp, 0.196922947431391188040943672442575686_dp]
integer, public :: get
integer, public :: i
integer, public, parameter :: k = 5
complex(kind=dp), public :: loc
integer, public :: n
real(kind=dp), public :: res(3,5)
complex(kind=dp), public :: scale
integer, public :: seed
complex(kind=dp), public :: x1
complex(kind=dp), public :: x2(3,4)
Call graph
test_nor_pdf_cdp calls pdf_normal, check, rvs_normal
check calls error_stop, optval
test_distribution_normal calls test_nor_pdf_cdp