test_string_sort – Fortran-lang/stdlib
test_string_sort Subroutine
36 statements
Source File
public subroutine test_string_sort(a, a_name, ltest)
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: a(0:)
character, intent(in) :: a_name
logical, intent(out) :: ltest
Calls
Called by
Contents
Variables
i rate t0 t1 tdiff valid
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public :: i
real(kind=dp), public :: rate
integer(kind=int64), public :: t0
integer(kind=int64), public :: t1
integer(kind=int64), public :: tdiff
logical, public :: valid
Call graph
test_string_sort calls verify_string_sort, sort, verify_string_reverse_sort
test_string_sorts calls test_string_sort