test_optval_cdp_arr – Fortran-lang/stdlib
test_optval_cdp_arr Subroutine
9 statements
Source File
public subroutine test_optval_cdp_arr(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
z1 z2
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public, dimension(2) :: z1
complex(kind=dp), public, dimension(2) :: z2
Call graph
test_optval_cdp_arr calls foo_cdp_arr, check
foo_cdp_arr calls optval