test_int_sort_indexes – Fortran-lang/stdlib
test_int_sort_indexes Subroutine
39 statements
Source File
public subroutine test_int_sort_indexes(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
d1 i index ltest
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public, allocatable :: d1(:)
integer(kind=int64), public :: i
integer(kind=int64), public, allocatable :: index(:)
logical, public :: ltest
Call graph
test_int_sort_indexes calls check, sort_index, test_int_sort_index, verify_sort
test_int_sort_index calls sort_index, verify_sort, verify_reverse_sort