test_uni_cdf_iint16 – Fortran-lang/stdlib
test_uni_cdf_iint16 Subroutine
16 statements
Source File
subroutine test_uni_cdf_iint16()
Arguments
None
Calls
Called by
Contents
Variables
ans get loc res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real, public, parameter :: ans(15) = [0.178217828, 0.178217828, 0.178217828, 0.465346545, 0.673267305, 0.247524753, 0.158415839, 0.792079210, 0.742574275, 0.574257433, 0.881188095, 0.663366318, 0.524752498, 0.623762369, 0.178217828]
integer, public :: get
integer(kind=int16), public :: loc
real, public :: res(3,5)
integer(kind=int16), public :: scale
integer, public :: seed
integer(kind=int16), public :: x1
integer(kind=int16), public :: x2(3,4)
Call graph
test_uni_cdf_iint16 calls uni_rvs, uni_cdf, check
check calls error_stop, optval
test_distribution_uniform calls test_uni_cdf_iint16