test_cdp – Fortran-lang/stdlib
test_cdp Subroutine
17 statements
Source File
subroutine test_cdp(x, x2)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
complex(kind=dp), intent(in) :: x2(:,:)
Calls
Called by
Contents
None
Call graph
test_cdp calls var, cov, check
check calls optval, error_stop
test_cov calls test_cdp