test_expon_cdf_csp – Fortran-lang/stdlib
test_expon_cdf_csp Subroutine
16 statements
Source File
subroutine test_expon_cdf_csp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public, parameter :: ans(15) = [7.83931265220552191922145459533155073E-0002_sp, 7.83931265220552191922145459533155073E-0002_sp, 7.83931265220552191922145459533155073E-0002_sp, 1.07845760925785109085652212151328215E-0002_sp, 0.672623038706161724678635394849362256_sp, 4.27264038113873579678831482902258168E-0002_sp, 0.179649132114996961326498233168917293_sp, 1.38375793985183014482681114776428612E-0002_sp, 3.49246365297941076158369468479748612E-0002_sp, 0.116869945417176368845403154176734792_sp, 0.468462732010133566674397830557697485_sp, 0.413506985517976634907329948218002431_sp, 0.665679674838121942273909342901808398_sp, 0.223748595107983772617787558595393205_sp, 0.337722969540396286456937689606849800_sp]
integer, public :: get
integer, public :: i
integer, public :: n
real(kind=sp), public :: res(3,5)
complex(kind=sp), public :: scale
integer, public :: seed
complex(kind=sp), public :: x1
complex(kind=sp), public :: x2(3,4)
Call graph
test_expon_cdf_csp calls rvs_exp, check, cdf_exp
check calls error_stop, optval
test_distribution_expon calls test_expon_cdf_csp