test_slice_gen – Fortran-lang/stdlib
test_slice_gen Subroutine
44 statements
Source File
public subroutine test_slice_gen(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
i j k offset test
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer, public, parameter :: offset = 3
character(len=*), public, parameter :: test = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
Call graph
test_slice_gen calls check_slicer
check_slicer calls reference_slice, check, slice, to_string
reference_slice calls optval, string_to_carray, carray_to_string