test_nor_cdf_cdp – Fortran-lang/stdlib
test_nor_cdf_cdp Subroutine
17 statements
Source File
subroutine test_nor_cdf_cdp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i loc n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: ans(15) = [1.07458136221563368133842063954746170E-0002_dp, 1.07458136221563368133842063954746170E-0002_dp, 1.07458136221563368133842063954746170E-0002_dp, 6.86483236063879585051085536740820057E-0002_dp, 7.95486634025192048896990048539218724E-0002_dp, 2.40523393996423661445007940057223384E-0002_dp, 3.35096768781160662250307446207445131E-0002_dp, 0.315778916661119434962814841317323376_dp, 0.446311293878359175362094845206410428_dp, 0.102010220821382542292905161748120877_dp, 7.66919007012121545175655727052974512E-0002_dp, 0.564690968410069125818268877247699603_dp, 0.708769523556518785240723539383512333_dp, 6.40553790808161720088070925562830659E-0002_dp, 5.39999153072107729358158443133850711E-0002_dp]
integer, public :: get
integer, public :: i
complex(kind=dp), public :: loc
integer, public :: n
real(kind=dp), public :: res(3,5)
complex(kind=dp), public :: scale
integer, public :: seed
complex(kind=dp), public :: x1
complex(kind=dp), public :: x2(3,4)
Call graph
test_nor_cdf_cdp calls check, cdf_normal, rvs_normal
check calls optval, error_stop
test_distribution_normal calls test_nor_cdf_cdp