test_expon_pdf_csp – Fortran-lang/stdlib
test_expon_pdf_csp Subroutine
16 statements
Source File
subroutine test_expon_pdf_csp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public, parameter :: ans(15) = [0.112097715784191810518066563334849515_sp, 0.112097715784191810518066563334849515_sp, 0.112097715784191810518066563334849515_sp, 4.72087485401191174735651518020251204E-0002_sp, 3.69705018439006691768174449531170720E-0002_sp, 8.69498969681198520061798177185735738E-0002_sp, 0.128007654288233028296342302153338001_sp, 1.13496395875758374774198906169957218E-0002_sp, 0.294260498264128747413785056084385424_sp, 4.66169813179250908948018478030960097E-0002_sp, 2.84438693906889813143446828488861951E-0002_sp, 0.161859307815385236742977105439660254_sp, 4.22904796362406579112752522035325397E-0002_sp, 0.176117981883470250164040199296778089_sp, 0.107352342201327219885025541854724060_sp]
integer, public :: get
integer, public :: i
integer, public :: n
real(kind=sp), public :: res(3,5)
complex(kind=sp), public :: scale
integer, public :: seed
complex(kind=sp), public :: x1
complex(kind=sp), public :: x2(3,4)
Call graph
test_expon_pdf_csp calls pdf_exp, rvs_exp, check
check calls error_stop, optval
test_distribution_expon calls test_expon_pdf_csp