test_int32 – Fortran-lang/stdlib
test_int32 Subroutine
119 statements
Source File
public subroutine test_int32(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
order x1 x2 x3 zero2_1 zero2_2 zero3_1 zero3_2 zero3_3
Variables
Type Visibility Attributes Name Initial
integer, public :: order
integer(kind=int32), public, parameter :: x1(5) = d1
integer(kind=int32), public, parameter :: x2(4,3) = d
integer(kind=int32), public, allocatable :: x3(:,:,:)
real(kind=dp), public, allocatable :: zero2_1(:)
real(kind=dp), public, allocatable :: zero2_2(:)
real(kind=dp), public, allocatable :: zero3_1(:,:)
real(kind=dp), public, allocatable :: zero3_2(:,:)
real(kind=dp), public, allocatable :: zero3_3(:,:)
Call graph
test_int32 calls moment, mean, check