test_shuffle – Fortran-lang/stdlib
test_shuffle Subroutine
22 statements
Source File
subroutine test_shuffle()
Arguments
None
Calls
Called by
Contents
Variables
get i n na put x xa z za
Variables
Type Visibility Attributes Name Initial
integer, public :: get
integer, public :: i
integer, public :: n(10)
integer, public, parameter :: na(10) = [10, 6, 9, 2, 8, 1, 3, 5, 7, 4]
integer, public :: put
real, public :: x(10)
real, public, parameter :: xa(10) = [5.0, 10.0, 9.0, 4.0, 3.0, 8.0, 2.0, 1.0, 7.0, 6.0]
complex, public :: z(10)
complex, public, parameter :: za(10) = [(8.0, 8.0), (7.0, 7.0), (4.0, 4.0), (1.0, 1.0), (5.0, 5.0), (9.0, 9.0), (6.0, 6.0), (3.0, 3.0), (2.0, 2.0), (10.0, 10.0)]
Call graph
test_shuffle calls shuffle, check
check calls optval, error_stop
test_distribution_uniform calls test_shuffle