test_append_prepend_array – Fortran-lang/stdlib
test_append_prepend_array Subroutine
28 statements
Source File
public subroutine test_append_prepend_array()
Arguments
None
Calls
Called by
Contents
Variables
first i j last reference_list stride work_list
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: first = -100
integer, public :: i
integer, public :: j
integer, public, parameter :: last = 100
type(stringlist_type), public :: reference_list
integer, public, parameter :: stride = 10
type(stringlist_type), public :: work_list
Call graph
test_append_prepend_array calls to_string, compare_list, check
compare_list calls to_string, check, fidx, bidx
check calls optval, error_stop
tester calls test_append_prepend_array