test_nor_cdf_rsp – Fortran-lang/stdlib
test_nor_cdf_rsp Subroutine
17 statements
Source File
subroutine test_nor_cdf_rsp()
Arguments
None
Calls
Called by
Contents
Variables
ans get i loc n res scale seed x1 x2
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public, parameter :: ans(15) = [7.50826305038441048487991102776953948E-0002_sp, 7.50826305038441048487991102776953948E-0002_sp, 7.50826305038441048487991102776953948E-0002_sp, 0.143119834108717983250834016885129863_sp, 0.241425421525703182028420560765471735_sp, 0.284345878626039240974266199229875972_sp, 0.233239836366015928845367994433532757_sp, 0.341059506137219171082517155967522896_sp, 0.353156850199835111081038166086606192_sp, 6.81066766396638231790017005897813244E-0002_sp, 4.38792331441682923984716366123285346E-0002_sp, 0.763679637882860826030745070304416929_sp, 0.363722187587355040667876190724308059_sp, 0.868187114884980488672309198087692444_sp, 0.626506799809652872401992867475200722_sp]
integer, public :: get
integer, public :: i
real(kind=sp), public :: loc
integer, public :: n
real(kind=sp), public :: res(3,5)
real(kind=sp), public :: scale
integer, public :: seed
real(kind=sp), public :: x1
real(kind=sp), public :: x2(3,4)
Call graph
test_nor_cdf_rsp calls cdf_normal, check, rvs_normal
check calls error_stop, optval
test_distribution_normal calls test_nor_cdf_rsp