test_insert_at_array – Fortran-lang/stdlib
test_insert_at_array Subroutine
26 statements
Source File
public subroutine test_insert_at_array()
Arguments
None
Calls
Called by
Contents
Variables
first i j last reference_list stride work_list
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: first = -100
integer, public :: i
integer, public :: j
integer, public, parameter :: last = 100
type(stringlist_type), public :: reference_list
integer, public, parameter :: stride = 4
type(stringlist_type), public :: work_list
Call graph
test_insert_at_array calls compare_list, bidx, fidx, to_string
compare_list calls bidx, fidx, to_string, check
check calls optval, error_stop
tester calls test_insert_at_array