test_diag_int8 – Fortran-lang/stdlib
test_diag_int8 Subroutine
12 statements
Source File
public subroutine test_diag_int8(error)
Arguments
Type Intent Optional Attributes Name
type(error_type), intent(out), allocatable :: error
Error handling
Calls
Contents
Variables
a i mask n
Variables
Type Visibility Attributes Name Initial
integer(kind=int8), public, allocatable :: a(:,:)
integer, public :: i
logical, public, allocatable :: mask(:,:)
integer, public, parameter :: n = 3
Call graph
test_diag_int8 calls diag, eye, check
eye calls optval