test_exponential_random_generator – Fortran-lang/stdlib
test_exponential_random_generator Subroutine
20 statements
Source File
subroutine test_exponential_random_generator()
Arguments
None
Calls
Called by
Contents
Variables
array_size chisq expct freq i j num
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: array_size = 1000
real(kind=dp), public :: chisq
real(kind=dp), public :: expct
integer, public :: freq(0:array_size)
integer, public :: i
integer, public :: j
integer, public, parameter :: num = 10000000
Call graph
test_exponential_random_generator calls rvs_exp, check
check calls error_stop, optval
test_distribution_expon calls test_exponential_random_generator