test_insert_at_string_3 – Fortran-lang/stdlib
test_insert_at_string_3 Subroutine
35 statements
Source File
public subroutine test_insert_at_string_3()
Arguments
None
Calls
Called by
Contents
Variables
current_length first i last string work_list
Variables
Type Visibility Attributes Name Initial
integer, public :: current_length
integer, public, parameter :: first = 2
integer, public :: i
integer, public, parameter :: last = 200
character(len=:), public, allocatable :: string
type(stringlist_type), public :: work_list
Call graph
test_insert_at_string_3 calls compare_list, to_string, bidx, check, fidx
compare_list calls to_string, bidx, check, fidx
check calls error_stop, optval
tester calls test_insert_at_string_3