var_all_1_rdp_rdp – Fortran-lang/stdlib
var_all_1_rdp_rdp Module Function
15 statements
Source File
function var_all_1_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_all_1_rdp_rdp calls optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp