var_mask_1_iint32_dp – Fortran-lang/stdlib
var_mask_1_iint32_dp Module Function
22 statements
Source File
function var_mask_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_mask_1_iint32_dp calls optval, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop