var_all_3_cqp_cqp – Fortran-lang/stdlib
var_all_3_cqp_cqp Module Function
15 statements
Source File
function var_all_3_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
complex(kind=qp), public :: mean
real(kind=qp), public :: n
Call graph
var_all_3_cqp_cqp calls optval
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64