var_all_4_csp_csp – Fortran-lang/stdlib
var_all_4_csp_csp Module Function
15 statements
Source File
function var_all_4_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
complex(kind=sp), public :: mean
real(kind=sp), public :: n
Call graph
var_all_4_csp_csp calls optval
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character