var_mask_1_iint64_dp – Fortran-lang/stdlib
var_mask_1_iint64_dp Module Function
22 statements
Source File
function var_mask_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_mask_1_iint64_dp calls error_stop, optval
error_stop calls error_stop
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32