var_mask_all_2_rqp_rqp – Fortran-lang/stdlib
var_mask_all_2_rqp_rqp Module Function
11 statements
Source File
function var_mask_all_2_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
real(kind=qp), public :: mean
real(kind=qp), public :: n
Call graph
var_mask_all_2_rqp_rqp calls optval
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64