var_2_iint8_dp – Fortran-lang/stdlib
var_2_iint8_dp Module Function
32 statements
Source File
function var_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public :: mean(merge(size(x,1),size(x,2),mask=1
real(kind=dp), public :: n
Call graph
var_2_iint8_dp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rdp, optval_rsp, optval_iint64, optval_cdp, optval_iint16, optval_iint32, optval_csp, optval_rqp, optval_cqp, optval_iint8, optval_ll1, optval_character