var_mask_all_3_cdp_cdp – Fortran-lang/stdlib
var_mask_all_3_cdp_cdp Module Function
11 statements
Source File
function var_mask_all_3_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
complex(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_mask_all_3_cdp_cdp calls optval
optval calls optval_iint16, optval_cdp, optval_rsp, optval_iint64, optval_character, optval_iint32, optval_iint8, optval_ll1, optval_rdp, optval_cqp, optval_rqp, optval_csp