var_mask_1_cqp_cqp – Fortran-lang/stdlib
var_mask_1_cqp_cqp Module Function
22 statements
Source File
function var_mask_1_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=qp), public :: mean
real(kind=qp), public :: n
Call graph
var_mask_1_cqp_cqp calls optval, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop