var_mask_2_iint8_dp – Fortran-lang/stdlib
var_mask_2_iint8_dp Module Function
28 statements
Source File
function var_mask_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public :: mean(merge(size(x,1),size(x,2),mask=1
real(kind=dp), public :: n(merge(size(x,1),size(x,2),mask=1
Call graph
var_mask_2_iint8_dp calls optval, error_stop
optval calls optval_character, optval_csp, optval_ll1, optval_cdp, optval_iint32, optval_cqp, optval_iint8, optval_rsp, optval_rdp, optval_iint16, optval_rqp, optval_iint64
error_stop calls error_stop