var_all_3_iint64_dp – Fortran-lang/stdlib
var_all_3_iint64_dp Module Function
14 statements
Source File
function var_all_3_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_all_3_iint64_dp calls optval
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp