var_mask_3_rqp_rqp – Fortran-lang/stdlib
var_mask_3_rqp_rqp Module Function
34 statements
Source File
function var_mask_3_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=qp), public :: mean(merge(size(x,1),size(x,2),mask=1
real(kind=qp), public :: n(merge(size(x,1),size(x,2),mask=1
Call graph
var_mask_3_rqp_rqp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp