var_all_4_rsp_rsp – Fortran-lang/stdlib
var_all_4_rsp_rsp Module Function
15 statements
Source File
function var_all_4_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
real(kind=sp), public :: mean
real(kind=sp), public :: n
Call graph
var_all_4_rsp_rsp calls optval
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32