var_mask_4_cdp_cdp – Fortran-lang/stdlib
var_mask_4_cdp_cdp Module Function
40 statements
Source File
function var_mask_4_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
complex(kind=dp), public :: mean(merge(size(x,1),size(x,2),mask=1
real(kind=dp), public :: n(merge(size(x,1),size(x,2),mask=1
Call graph
var_mask_4_cdp_cdp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp