var_mask_all_2_iint16_dp – Fortran-lang/stdlib
var_mask_all_2_iint16_dp Module Function
10 statements
Source File
function var_mask_all_2_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
Calls
Contents
Variables
mean n
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: mean
real(kind=dp), public :: n
Call graph
var_mask_all_2_iint16_dp calls optval
optval calls optval_iint8, optval_iint64, optval_rqp, optval_ll1, optval_rsp, optval_cqp, optval_iint16, optval_rdp, optval_cdp, optval_csp, optval_character, optval_iint32