var_4_iint64_dp – Fortran-lang/stdlib
var_4_iint64_dp Module Function
44 statements
Source File
function var_4_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
Calls
Contents
Variables
i mean n
Variables
Type Visibility Attributes Name Initial
integer, public :: i
real(kind=dp), public :: mean(merge(size(x,1),size(x,2),mask=1
real(kind=dp), public :: n
Call graph
var_4_iint64_dp calls error_stop, optval
error_stop calls error_stop
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_iint8, optval_iint32, optval_cqp, optval_rsp