verify_string_reverse_sort – Fortran-lang/stdlib
verify_string_reverse_sort Subroutine
12 statements
Source File
public subroutine verify_string_reverse_sort(a, valid, i)
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: a(0:)
logical, intent(out) :: valid
integer(kind=int64), intent(out) :: i
Called by
Contents
Variables
n
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public :: n
Call graph
test_string_sort calls verify_string_reverse_sort
test_string_ord_sort calls verify_string_reverse_sort
test_string_sorts calls test_string_sort
test_string_ord_sorts calls test_string_ord_sort