all_close – Fortran-lang/stdlib
all_close Interface
experimental
62 statements
Source File
public interface all_close
Returns a boolean scalar where two arrays are element-wise equal within a tolerance. (Specification)
Called by
Contents
Functions
all_close_1_cdp all_close_1_csp all_close_1_rdp all_close_1_rsp all_close_2_cdp all_close_2_csp all_close_2_rdp all_close_2_rsp all_close_3_cdp all_close_3_csp all_close_3_rdp all_close_3_rsp
Functions
private pure module function all_close_1_cdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: a(:)
complex(kind=dp), intent(in) :: b(:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_1_csp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: a(:)
complex(kind=sp), intent(in) :: b(:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_1_rdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a(:)
real(kind=dp), intent(in) :: b(:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_1_rsp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a(:)
real(kind=sp), intent(in) :: b(:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_2_cdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: a(:,:)
complex(kind=dp), intent(in) :: b(:,:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_2_csp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: a(:,:)
complex(kind=sp), intent(in) :: b(:,:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_2_rdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a(:,:)
real(kind=dp), intent(in) :: b(:,:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_2_rsp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a(:,:)
real(kind=sp), intent(in) :: b(:,:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_3_cdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: a(:,:,:)
complex(kind=dp), intent(in) :: b(:,:,:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_3_csp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: a(:,:,:)
complex(kind=sp), intent(in) :: b(:,:,:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_3_rdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a(:,:,:)
real(kind=dp), intent(in) :: b(:,:,:)
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private pure module function all_close_3_rsp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a(:,:,:)
real(kind=sp), intent(in) :: b(:,:,:)
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
Call graph
test_all_close_cmplx_dp calls all_close
test_diff_real_sp calls all_close
test_diff_real_dp calls all_close
test_all_close_real_sp calls all_close
test_all_close_cmplx_sp calls all_close
test_arange_real_sp calls all_close
test_arange_real_dp calls all_close
test_all_close_real_dp calls all_close