arange – Fortran-lang/stdlib
arange Interface
experimental
32 statements
Source File
public interface arange
arange creates a one-dimensional array of the integer/real type with fixed-spaced values of given spacing, within a given interval. (Specification)
Called by
Contents
Functions
arange_i_int16 arange_i_int32 arange_i_int64 arange_i_int8 arange_r_dp arange_r_sp
Functions
private pure module function arange_i_int16(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: start
integer(kind=int16), intent(in), optional :: end
integer(kind=int16), intent(in), optional :: step
Return Value integer(kind=int16),allocatable, (:)
private pure module function arange_i_int32(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: start
integer(kind=int32), intent(in), optional :: end
integer(kind=int32), intent(in), optional :: step
Return Value integer(kind=int32),allocatable, (:)
private pure module function arange_i_int64(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: start
integer(kind=int64), intent(in), optional :: end
integer(kind=int64), intent(in), optional :: step
Return Value integer(kind=int64),allocatable, (:)
private pure module function arange_i_int8(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: start
integer(kind=int8), intent(in), optional :: end
integer(kind=int8), intent(in), optional :: step
Return Value integer(kind=int8),allocatable, (:)
private pure module function arange_r_dp(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in), optional :: end
real(kind=dp), intent(in), optional :: step
Return Value real(kind=dp),allocatable, (:)
private pure module function arange_r_sp(start, end, step) result(result)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in), optional :: end
real(kind=sp), intent(in), optional :: step
Return Value real(kind=sp),allocatable, (:)
Call graph
test_arange_int_int32 calls arange
test_arange_real_sp calls arange
test_arange_int_int16 calls arange
test_arg_sp calls arange
test_argpi_sp calls arange
test_arange_int_int8 calls arange
test_arg_dp calls arange
test_argd_sp calls arange
test_argpi_dp calls arange
test_arange_int_int64 calls arange
test_argd_dp calls arange
test_arange_real_dp calls arange