bidx – Fortran-lang/stdlib
bidx Interface
experimental
3 statements
Source File
public interface bidx
Returns an instance of type 'stringlist_index_type' representing backward index Specifications
Called by
Contents
Module Procedures
backward_index
Module Procedures
private pure function backward_index(idx)
Returns an instance of type 'stringlist_index_type' representing backward index 'idx'
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: idx
Return Value type(stringlist_index_type)
Call graph
test_insert_at_list calls bidx, compare_list
test_insert_at_string_1 calls bidx, compare_list
test_insert_at_string_2 calls bidx, compare_list
test_insert_at_string_3 calls bidx, compare_list
test_insert_at_array calls bidx, compare_list
test_append_prepend_string calls bidx, compare_list
compare_list calls bidx
tester calls test_insert_at_list, test_insert_at_string_1, test_insert_at_string_2, test_insert_at_string_3, test_insert_at_array, test_append_prepend_string, test_append_prepend_array, test_append_prepend_list
test_append_prepend_array calls compare_list
test_append_prepend_list calls compare_list