cdf_exp – Fortran-lang/stdlib
cdf_exp Interface
6 statements
Source File
public interface cdf_exp
Version experimental
Exponential Cumulative Distribution Function (Specification)
Called by
Contents
Module Procedures
cdf_exp_rsp cdf_exp_rdp cdf_exp_csp cdf_exp_cdp
Module Procedures
private impure elemental function cdf_exp_rsp(x, lambda) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x
real(kind=sp), intent(in) :: lambda
Return Value real(kind=sp)
private impure elemental function cdf_exp_rdp(x, lambda) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
real(kind=dp), intent(in) :: lambda
Return Value real(kind=dp)
private impure elemental function cdf_exp_csp(x, lambda) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x
complex(kind=sp), intent(in) :: lambda
Return Value real(kind=sp)
private impure elemental function cdf_exp_cdp(x, lambda) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x
complex(kind=dp), intent(in) :: lambda
Return Value real(kind=dp)
Call graph
test_expon_cdf_csp calls cdf_exp
test_expon_cdf_rsp calls cdf_exp
test_expon_cdf_cdp calls cdf_exp
test_expon_cdf_rdp calls cdf_exp
test_distribution_expon calls test_expon_cdf_csp, test_expon_cdf_rsp, test_expon_cdf_cdp, test_expon_cdf_rdp