clip – Fortran-lang/stdlib
clip Interface
8 statements
Source File
public interface clip
Called by
Contents
Module Procedures
clip_int8 clip_int16 clip_int32 clip_int64 clip_sp clip_dp
Module Procedures
private elemental function clip_int8(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x
integer(kind=int8), intent(in) :: xmin
integer(kind=int8), intent(in) :: xmax
Return Value integer(kind=int8)
private elemental function clip_int16(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x
integer(kind=int16), intent(in) :: xmin
integer(kind=int16), intent(in) :: xmax
Return Value integer(kind=int16)
private elemental function clip_int32(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x
integer(kind=int32), intent(in) :: xmin
integer(kind=int32), intent(in) :: xmax
Return Value integer(kind=int32)
private elemental function clip_int64(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x
integer(kind=int64), intent(in) :: xmin
integer(kind=int64), intent(in) :: xmax
Return Value integer(kind=int64)
private elemental function clip_sp(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x
real(kind=sp), intent(in) :: xmin
real(kind=sp), intent(in) :: xmax
Return Value real(kind=sp)
private elemental function clip_dp(x, xmin, xmax) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
real(kind=dp), intent(in) :: xmin
real(kind=dp), intent(in) :: xmax
Return Value real(kind=dp)
Call graph
test_clip_int64 calls clip
test_clip_rsp_bounds calls clip
test_clip_int32_bounds calls clip
test_clip_rsp calls clip
test_clip_int32 calls clip
test_clip_rdp_bounds calls clip
test_clip_int16 calls clip
test_clip_int16_bounds calls clip
test_clip_rdp calls clip
test_clip_int8 calls clip
test_clip_int8_bounds calls clip
test_clip_int64_bounds calls clip