cov – Fortran-lang/stdlib
cov Interface
experimental
226 statements
Source File
public interface cov
Covariance of array elements (Specification)
Called by
Contents
Functions
cov_1_cdp_cdp cov_1_csp_csp cov_1_iint16_dp cov_1_iint32_dp cov_1_iint64_dp cov_1_iint8_dp cov_1_rdp_rdp cov_1_rsp_rsp cov_2_cdp_cdp cov_2_csp_csp cov_2_iint16_dp cov_2_iint32_dp cov_2_iint64_dp cov_2_iint8_dp cov_2_rdp_rdp cov_2_rsp_rsp cov_mask_1_cdp_cdp cov_mask_1_csp_csp cov_mask_1_iint16_dp cov_mask_1_iint32_dp cov_mask_1_iint64_dp cov_mask_1_iint8_dp cov_mask_1_rdp_rdp cov_mask_1_rsp_rsp cov_mask_2_cdp_cdp cov_mask_2_csp_csp cov_mask_2_iint16_dp cov_mask_2_iint32_dp cov_mask_2_iint64_dp cov_mask_2_iint8_dp cov_mask_2_rdp_rdp cov_mask_2_rsp_rsp
Functions
private module function cov_1_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
private module function cov_1_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_1_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
private module function cov_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value complex(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value complex(kind=sp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_2_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_1_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
private module function cov_mask_1_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
private module function cov_mask_1_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
private module function cov_mask_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value complex(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value complex(kind=sp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)(merge(size(x,1),size(x,2),mask=1
private module function cov_mask_2_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)(merge(size(x,1),size(x,2),mask=1
Call graph
test_csp calls cov
test_int32 calls cov
test_int64 calls cov
test_dp calls cov
test_cdp calls cov
test_sp calls cov
test_cov calls test_csp, test_int32, test_int64, test_dp, test_cdp, test_sp