diag – Fortran-lang/stdlib
diag Interface
experimental
146 statements
Source File
public interface diag
Creates a diagonal array or extract the diagonal elements of an array (Specification)
Called by
Contents
Functions
diag_cdp diag_cdp_k diag_cdp_mat diag_cdp_mat_k diag_csp diag_csp_k diag_csp_mat diag_csp_mat_k diag_iint16 diag_iint16_k diag_iint16_mat diag_iint16_mat_k diag_iint32 diag_iint32_k diag_iint32_mat diag_iint32_mat_k diag_iint64 diag_iint64_k diag_iint64_mat diag_iint64_mat_k diag_iint8 diag_iint8_k diag_iint8_mat diag_iint8_mat_k diag_rdp diag_rdp_k diag_rdp_mat diag_rdp_mat_k diag_rsp diag_rsp_k diag_rsp_mat diag_rsp_mat_k
Functions
private module function diag_cdp(v) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: v(:)
Return Value complex(kind=dp)(size(v),size(v))
private module function diag_cdp_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: v(:)
integer, intent(in) :: k
Return Value complex(kind=dp)(size(v)+abs(k),size(v)+abs(k))
private module function diag_cdp_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value complex(kind=dp)(minval(shape(A)))
private module function diag_cdp_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value complex(kind=dp)(minval(shape(A))-abs(k))
private module function diag_csp(v) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: v(:)
Return Value complex(kind=sp)(size(v),size(v))
private module function diag_csp_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: v(:)
integer, intent(in) :: k
Return Value complex(kind=sp)(size(v)+abs(k),size(v)+abs(k))
private module function diag_csp_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value complex(kind=sp)(minval(shape(A)))
private module function diag_csp_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value complex(kind=sp)(minval(shape(A))-abs(k))
private module function diag_iint16(v) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: v(:)
Return Value integer(kind=int16)(size(v),size(v))
private module function diag_iint16_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: v(:)
integer, intent(in) :: k
Return Value integer(kind=int16)(size(v)+abs(k),size(v)+abs(k))
private module function diag_iint16_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value integer(kind=int16)(minval(shape(A)))
private module function diag_iint16_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value integer(kind=int16)(minval(shape(A))-abs(k))
private module function diag_iint32(v) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: v(:)
Return Value integer(kind=int32)(size(v),size(v))
private module function diag_iint32_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: v(:)
integer, intent(in) :: k
Return Value integer(kind=int32)(size(v)+abs(k),size(v)+abs(k))
private module function diag_iint32_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value integer(kind=int32)(minval(shape(A)))
private module function diag_iint32_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value integer(kind=int32)(minval(shape(A))-abs(k))
private module function diag_iint64(v) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: v(:)
Return Value integer(kind=int64)(size(v),size(v))
private module function diag_iint64_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: v(:)
integer, intent(in) :: k
Return Value integer(kind=int64)(size(v)+abs(k),size(v)+abs(k))
private module function diag_iint64_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value integer(kind=int64)(minval(shape(A)))
private module function diag_iint64_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value integer(kind=int64)(minval(shape(A))-abs(k))
private module function diag_iint8(v) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: v(:)
Return Value integer(kind=int8)(size(v),size(v))
private module function diag_iint8_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: v(:)
integer, intent(in) :: k
Return Value integer(kind=int8)(size(v)+abs(k),size(v)+abs(k))
private module function diag_iint8_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value integer(kind=int8)(minval(shape(A)))
private module function diag_iint8_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value integer(kind=int8)(minval(shape(A))-abs(k))
private module function diag_rdp(v) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: v(:)
Return Value real(kind=dp)(size(v),size(v))
private module function diag_rdp_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: v(:)
integer, intent(in) :: k
Return Value real(kind=dp)(size(v)+abs(k),size(v)+abs(k))
private module function diag_rdp_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value real(kind=dp)(minval(shape(A)))
private module function diag_rdp_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value real(kind=dp)(minval(shape(A))-abs(k))
private module function diag_rsp(v) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: v(:)
Return Value real(kind=sp)(size(v),size(v))
private module function diag_rsp_k(v, k) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: v(:)
integer, intent(in) :: k
Return Value real(kind=sp)(size(v)+abs(k),size(v)+abs(k))
private module function diag_rsp_mat(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value real(kind=sp)(minval(shape(A)))
private module function diag_rsp_mat_k(A, k) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
integer, intent(in) :: k
Return Value real(kind=sp)(minval(shape(A))-abs(k))
Call graph
test_diag_int64 calls diag
test_diag_cdp calls diag
test_diag_rsp_k calls diag
test_trace_rdp calls diag
test_diag_int16 calls diag
test_diag_int32 calls diag
test_diag_rdp calls diag
test_diag_int8 calls diag
test_diag_rsp calls diag
test_trace_rsp calls diag
test_eye calls diag
test_diag_csp calls diag