diff – Fortran-lang/stdlib
diff Interface
experimental
74 statements
Source File
public interface diff
Computes differences between adjacent elements of an array. (Specification)
Called by
Contents
Functions
diff_1_dp diff_1_int16 diff_1_int32 diff_1_int64 diff_1_int8 diff_1_sp diff_2_dp diff_2_int16 diff_2_int32 diff_2_int64 diff_2_int8 diff_2_sp
Functions
private pure module function diff_1_dp(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in), optional :: n
real(kind=dp), intent(in), optional :: prepend(:)
real(kind=dp), intent(in), optional :: append(:)
Return Value real(kind=dp),allocatable, (:)
private pure module function diff_1_int16(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in), optional :: n
integer(kind=int16), intent(in), optional :: prepend(:)
integer(kind=int16), intent(in), optional :: append(:)
Return Value integer(kind=int16),allocatable, (:)
private pure module function diff_1_int32(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in), optional :: n
integer(kind=int32), intent(in), optional :: prepend(:)
integer(kind=int32), intent(in), optional :: append(:)
Return Value integer(kind=int32),allocatable, (:)
private pure module function diff_1_int64(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in), optional :: n
integer(kind=int64), intent(in), optional :: prepend(:)
integer(kind=int64), intent(in), optional :: append(:)
Return Value integer(kind=int64),allocatable, (:)
private pure module function diff_1_int8(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in), optional :: n
integer(kind=int8), intent(in), optional :: prepend(:)
integer(kind=int8), intent(in), optional :: append(:)
Return Value integer(kind=int8),allocatable, (:)
private pure module function diff_1_sp(x, n, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in), optional :: n
real(kind=sp), intent(in), optional :: prepend(:)
real(kind=sp), intent(in), optional :: append(:)
Return Value real(kind=sp),allocatable, (:)
private pure module function diff_2_dp(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
real(kind=dp), intent(in), optional :: prepend(:,:)
real(kind=dp), intent(in), optional :: append(:,:)
Return Value real(kind=dp),allocatable, (:,:)
private pure module function diff_2_int16(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
integer(kind=int16), intent(in), optional :: prepend(:,:)
integer(kind=int16), intent(in), optional :: append(:,:)
Return Value integer(kind=int16),allocatable, (:,:)
private pure module function diff_2_int32(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
integer(kind=int32), intent(in), optional :: prepend(:,:)
integer(kind=int32), intent(in), optional :: append(:,:)
Return Value integer(kind=int32),allocatable, (:,:)
private pure module function diff_2_int64(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
integer(kind=int64), intent(in), optional :: prepend(:,:)
integer(kind=int64), intent(in), optional :: append(:,:)
Return Value integer(kind=int64),allocatable, (:,:)
private pure module function diff_2_int8(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
integer(kind=int8), intent(in), optional :: prepend(:,:)
integer(kind=int8), intent(in), optional :: append(:,:)
Return Value integer(kind=int8),allocatable, (:,:)
private pure module function diff_2_sp(x, n, dim, prepend, append) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in), optional :: n
integer, intent(in), optional :: dim
real(kind=sp), intent(in), optional :: prepend(:,:)
real(kind=sp), intent(in), optional :: append(:,:)
Return Value real(kind=sp),allocatable, (:,:)
Call graph
test_diff_int_int16 calls diff
test_diff_int_int32 calls diff
test_diff_int_int64 calls diff
test_diff_real_sp calls diff
test_diff_int_int8 calls diff
test_diff_real_dp calls diff