fidx – Fortran-lang/stdlib
fidx Interface
experimental
3 statements
Source File
public interface fidx
Returns an instance of type 'stringlist_index_type' representing forward index Specifications
Called by
Contents
Module Procedures
forward_index
Module Procedures
private pure function forward_index(idx)
Returns an instance of type 'stringlist_index_type' representing forward index 'idx'
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: idx
Return Value type(stringlist_index_type)
Call graph
compare_list calls fidx
test_insert_at_string_3 calls fidx, compare_list
test_insert_at_array calls fidx, compare_list
test_append_prepend_string calls fidx, compare_list
test_insert_at_string_2 calls fidx, compare_list
test_insert_at_string_1 calls fidx, compare_list
test_insert_at_list calls fidx, compare_list
test_append_prepend_list calls compare_list
test_append_prepend_array calls compare_list
tester calls test_append_prepend_string, test_append_prepend_list, test_append_prepend_array, test_insert_at_string_3, test_insert_at_array, test_insert_at_string_2, test_insert_at_string_1, test_insert_at_list