gauss_legendre – Fortran-lang/stdlib
gauss_legendre Interface
experimental
6 statements
Source File
public interface gauss_legendre
Computes Gauss-Legendre quadrature nodes and weights.
Called by
Contents
Subroutines
gauss_legendre_fp64
Subroutines
private pure module subroutine gauss_legendre_fp64(x, w, interval)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: x(:)
real(kind=dp), intent(out) :: w(:)
real(kind=dp), intent(in), optional :: interval(2)
Call graph
test_gauss_analytic calls gauss_legendre
test_gauss_5 calls gauss_legendre
test_gauss_64 calls gauss_legendre
test_gauss_32 calls gauss_legendre