is_close – Fortran-lang/stdlib
is_close Interface
22 statements
Source File
public interface is_close
Returns a boolean scalar/array where two scalar/arrays are element-wise equal within a tolerance. (Specification)
Called by
Contents
Functions
is_close_cdp is_close_csp is_close_rdp is_close_rsp
Functions
private elemental module function is_close_cdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: a
complex(kind=dp), intent(in) :: b
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private elemental module function is_close_csp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: a
complex(kind=sp), intent(in) :: b
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private elemental module function is_close_rdp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
real(kind=dp), intent(in), optional :: rel_tol
real(kind=dp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
private elemental module function is_close_rsp(a, b, rel_tol, abs_tol, equal_nan) result(close)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
real(kind=sp), intent(in), optional :: rel_tol
real(kind=sp), intent(in), optional :: abs_tol
logical, intent(in), optional :: equal_nan
Return Value logical
Call graph
test_is_close_cmplx_sp calls is_close
test_is_close_real_sp calls is_close
test_is_close_cmplx_dp calls is_close
test_is_close_real_dp calls is_close