is_diagonal – Fortran-lang/stdlib
is_diagonal Interface
experimental
10 statements
Source File
public interface is_diagonal
Checks if a matrix (rank-2 array) is diagonal (Specification)
Called by
Contents
Module Procedures
is_diagonal_rsp is_diagonal_rdp is_diagonal_csp is_diagonal_cdp is_diagonal_iint8 is_diagonal_iint16 is_diagonal_iint32 is_diagonal_iint64
Module Procedures
private pure function is_diagonal_rsp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_rdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_csp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_cdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_iint8(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_iint16(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_iint32(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value logical
private pure function is_diagonal_iint64(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value logical
Call graph
test_is_diagonal_int32 calls is_diagonal
test_is_diagonal_int16 calls is_diagonal
test_is_diagonal_cdp calls is_diagonal
test_is_diagonal_int8 calls is_diagonal
test_is_diagonal_csp calls is_diagonal
test_is_diagonal_rsp calls is_diagonal
test_is_diagonal_rdp calls is_diagonal
test_is_diagonal_int64 calls is_diagonal