is_hessenberg – Fortran-lang/stdlib
is_hessenberg Interface
experimental
10 statements
Source File
public interface is_hessenberg
Checks if a matrix (rank-2 array) is Hessenberg (Specification)
Called by
Contents
Module Procedures
is_Hessenberg_rsp is_Hessenberg_rdp is_Hessenberg_csp is_Hessenberg_cdp is_Hessenberg_iint8 is_Hessenberg_iint16 is_Hessenberg_iint32 is_Hessenberg_iint64
Module Procedures
private function is_hessenberg_rsp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_rdp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_csp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_cdp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_iint8(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_iint16(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_iint32(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_hessenberg_iint64(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
Call graph
test_is_hessenberg_cdp calls is_hessenberg
test_is_hessenberg_int64 calls is_hessenberg
test_is_hessenberg_csp calls is_hessenberg
test_is_hessenberg_rdp calls is_hessenberg
test_is_hessenberg_int8 calls is_hessenberg
test_is_hessenberg_rsp calls is_hessenberg
test_is_hessenberg_int32 calls is_hessenberg
test_is_hessenberg_int16 calls is_hessenberg