is_hermitian – Fortran-lang/stdlib
is_hermitian Interface
experimental
10 statements
Source File
public interface is_hermitian
Checks if a matrix (rank-2 array) is Hermitian (Specification)
Called by
Contents
Module Procedures
is_hermitian_rsp is_hermitian_rdp is_hermitian_csp is_hermitian_cdp is_hermitian_iint8 is_hermitian_iint16 is_hermitian_iint32 is_hermitian_iint64
Module Procedures
private pure function is_hermitian_rsp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_rdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_csp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_cdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_iint8(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_iint16(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_iint32(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value logical
private pure function is_hermitian_iint64(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value logical
Call graph
test_is_hermitian_int8 calls is_hermitian
test_is_hermitian_cdp calls is_hermitian
test_is_hermitian_csp calls is_hermitian
test_is_hermitian_rsp calls is_hermitian
test_is_hermitian_rdp calls is_hermitian
test_is_hermitian_int32 calls is_hermitian
test_is_hermitian_int16 calls is_hermitian
test_is_hermitian_int64 calls is_hermitian