is_skew_symmetric – Fortran-lang/stdlib
is_skew_symmetric Interface
experimental
10 statements
Source File
public interface is_skew_symmetric
Checks if a matrix (rank-2 array) is skew-symmetric (Specification)
Called by
Contents
Module Procedures
is_skew_symmetric_rsp is_skew_symmetric_rdp is_skew_symmetric_csp is_skew_symmetric_cdp is_skew_symmetric_iint8 is_skew_symmetric_iint16 is_skew_symmetric_iint32 is_skew_symmetric_iint64
Module Procedures
private pure function is_skew_symmetric_rsp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_rdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_csp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_cdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_iint8(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_iint16(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_iint32(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value logical
private pure function is_skew_symmetric_iint64(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value logical
Call graph
test_is_skew_symmetric_int64 calls is_skew_symmetric
test_is_skew_symmetric_int8 calls is_skew_symmetric
test_is_skew_symmetric_rsp calls is_skew_symmetric
test_is_skew_symmetric_int32 calls is_skew_symmetric
test_is_skew_symmetric_csp calls is_skew_symmetric
test_is_skew_symmetric_int16 calls is_skew_symmetric
test_is_skew_symmetric_rdp calls is_skew_symmetric
test_is_skew_symmetric_cdp calls is_skew_symmetric