is_square – Fortran-lang/stdlib
is_square Interface
experimental
10 statements
Source File
public interface is_square
Checks if a matrix (rank-2 array) is square (Specification)
Called by
Contents
Module Procedures
is_square_rsp is_square_rdp is_square_csp is_square_cdp is_square_iint8 is_square_iint16 is_square_iint32 is_square_iint64
Module Procedures
private pure function is_square_rsp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_rdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_csp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_cdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_iint8(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_iint16(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_iint32(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value logical
private pure function is_square_iint64(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value logical
Call graph
test_is_square_rdp calls is_square
test_is_square_int64 calls is_square
test_is_square_int32 calls is_square
test_is_square_cdp calls is_square
test_is_square_rsp calls is_square
test_is_square_int8 calls is_square
test_is_square_csp calls is_square
test_is_square_int16 calls is_square