is_triangular – Fortran-lang/stdlib
is_triangular Interface
experimental
10 statements
Source File
public interface is_triangular
Checks if a matrix (rank-2 array) is triangular (Specification)
Called by
Contents
Module Procedures
is_triangular_rsp is_triangular_rdp is_triangular_csp is_triangular_cdp is_triangular_iint8 is_triangular_iint16 is_triangular_iint32 is_triangular_iint64
Module Procedures
private function is_triangular_rsp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_rdp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_csp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_cdp(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_iint8(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_iint16(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_iint32(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
private function is_triangular_iint64(A, uplo) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
character, intent(in) :: uplo
Return Value logical
Call graph
test_is_triangular_int8 calls is_triangular
test_is_triangular_int16 calls is_triangular
test_is_triangular_int32 calls is_triangular
test_is_triangular_int64 calls is_triangular
test_is_triangular_rdp calls is_triangular
test_is_triangular_cdp calls is_triangular
test_is_triangular_csp calls is_triangular
test_is_triangular_rsp calls is_triangular