loadtxt – Fortran-lang/stdlib
loadtxt Interface
12 statements
Source File
public interface loadtxt
Calls
Contents
Module Procedures
loadtxt_rsp loadtxt_rdp loadtxt_rqp loadtxt_iint8 loadtxt_iint16 loadtxt_iint32 loadtxt_iint64 loadtxt_csp loadtxt_cdp loadtxt_cqp
Module Procedures
private subroutine loadtxt_rsp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=sp), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_rdp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=dp), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_rqp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=qp), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_iint8(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int8), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_iint16(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int16), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_iint32(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int32), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_iint64(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int64), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_csp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=sp), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_cdp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=dp), intent(out), allocatable :: d(:,:)
private subroutine loadtxt_cqp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=qp), intent(out), allocatable :: d(:,:)
Call graph
loadtxt calls loadtxt_rdp, loadtxt_rqp, loadtxt_iint8, loadtxt_cqp, loadtxt_rsp, loadtxt_iint32, loadtxt_iint16, loadtxt_cdp, loadtxt_csp, loadtxt_iint64
loadtxt_rdp calls number_of_rows_numeric, number_of_columns
loadtxt_rqp calls number_of_rows_numeric, number_of_columns
loadtxt_iint8 calls number_of_rows_numeric, number_of_columns
loadtxt_cqp calls number_of_rows_numeric, number_of_columns
loadtxt_rsp calls number_of_rows_numeric, number_of_columns
loadtxt_iint32 calls number_of_rows_numeric, number_of_columns
loadtxt_iint16 calls number_of_rows_numeric, number_of_columns
loadtxt_cdp calls number_of_rows_numeric, number_of_columns
loadtxt_csp calls number_of_rows_numeric, number_of_columns
loadtxt_iint64 calls number_of_rows_numeric, number_of_columns
number_of_columns calls is_blank