logspace – Fortran-lang/stdlib
logspace Interface
Experimental
176 statements
Source File
public interface logspace
Create rank 1 array of logarithmically spaced elements from basestart to baseend. If the number of elements is not specified, create an array with size 50. If n is a negative value, return an array with size 0. If n = 1, return an array whose only element is base**end. If no base is specified, logspace will default to using a base of 10
(Specification)
Called by
Contents
Functions
logspace_1_cdp_default logspace_1_cdp_n logspace_1_cdp_n_cbase logspace_1_cdp_n_ibase logspace_1_cdp_n_rbase logspace_1_csp_default logspace_1_csp_n logspace_1_csp_n_cbase logspace_1_csp_n_ibase logspace_1_csp_n_rbase logspace_1_iint32_default logspace_1_iint32_n logspace_1_iint32_n_cdpbase logspace_1_iint32_n_cspbase logspace_1_iint32_n_ibase logspace_1_iint32_n_rdpbase logspace_1_iint32_n_rspbase logspace_1_rdp_default logspace_1_rdp_n logspace_1_rdp_n_cbase logspace_1_rdp_n_ibase logspace_1_rdp_n_rbase logspace_1_rsp_default logspace_1_rsp_n logspace_1_rsp_n_cbase logspace_1_rsp_n_ibase logspace_1_rsp_n_rbase
Functions
private pure module function logspace_1_cdp_default(start, end) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: start
complex(kind=dp), intent(in) :: end
Return Value complex(kind=dp)(DEFAULT_LOGSPACE_LENGTH)
private pure module function logspace_1_cdp_n(start, end, n) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: start
complex(kind=dp), intent(in) :: end
integer, intent(in) :: n
Return Value complex(kind=dp)(max(n,0))
private pure module function logspace_1_cdp_n_cbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: start
complex(kind=dp), intent(in) :: end
integer, intent(in) :: n
complex(kind=dp), intent(in) :: base
Return Value complex(kind=dp)(max(n,0))
private pure module function logspace_1_cdp_n_ibase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: start
complex(kind=dp), intent(in) :: end
integer, intent(in) :: n
integer, intent(in) :: base
Return Value complex(kind=dp)(max(n,0))
private pure module function logspace_1_cdp_n_rbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: start
complex(kind=dp), intent(in) :: end
integer, intent(in) :: n
real(kind=dp), intent(in) :: base
Return Value complex(kind=dp)(max(n,0))
private pure module function logspace_1_csp_default(start, end) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: start
complex(kind=sp), intent(in) :: end
Return Value complex(kind=sp)(DEFAULT_LOGSPACE_LENGTH)
private pure module function logspace_1_csp_n(start, end, n) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: start
complex(kind=sp), intent(in) :: end
integer, intent(in) :: n
Return Value complex(kind=sp)(max(n,0))
private pure module function logspace_1_csp_n_cbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: start
complex(kind=sp), intent(in) :: end
integer, intent(in) :: n
complex(kind=sp), intent(in) :: base
Return Value complex(kind=sp)(max(n,0))
private pure module function logspace_1_csp_n_ibase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: start
complex(kind=sp), intent(in) :: end
integer, intent(in) :: n
integer, intent(in) :: base
Return Value complex(kind=sp)(max(n,0))
private pure module function logspace_1_csp_n_rbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: start
complex(kind=sp), intent(in) :: end
integer, intent(in) :: n
real(kind=sp), intent(in) :: base
Return Value complex(kind=sp)(max(n,0))
private pure module function logspace_1_iint32_default(start, end) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
Return Value real(kind=dp)(DEFAULT_LOGSPACE_LENGTH)
private pure module function logspace_1_iint32_n(start, end, n) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
Return Value real(kind=dp)(n)
private pure module function logspace_1_iint32_n_cdpbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
complex(kind=dp), intent(in) :: base
Return Value complex(kind=dp)(max(n,0))
private pure module function logspace_1_iint32_n_cspbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
complex(kind=sp), intent(in) :: base
Return Value complex(kind=sp)(max(n,0))
private pure module function logspace_1_iint32_n_ibase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
integer, intent(in) :: base
Return Value integer(max(n,0))
private pure module function logspace_1_iint32_n_rdpbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
real(kind=dp), intent(in) :: base
Return Value real(kind=dp)(max(n,0))
private pure module function logspace_1_iint32_n_rspbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start
integer, intent(in) :: end
integer, intent(in) :: n
real(kind=sp), intent(in) :: base
Return Value real(kind=sp)(max(n,0))
private pure module function logspace_1_rdp_default(start, end) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in) :: end
Return Value real(kind=dp)(DEFAULT_LOGSPACE_LENGTH)
private pure module function logspace_1_rdp_n(start, end, n) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in) :: end
integer, intent(in) :: n
Return Value real(kind=dp)(max(n,0))
private pure module function logspace_1_rdp_n_cbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in) :: end
integer, intent(in) :: n
complex(kind=dp), intent(in) :: base
Return Value real(kind=dp)(max(n,0))
private pure module function logspace_1_rdp_n_ibase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in) :: end
integer, intent(in) :: n
integer, intent(in) :: base
Return Value real(kind=dp)(max(n,0))
private pure module function logspace_1_rdp_n_rbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: start
real(kind=dp), intent(in) :: end
integer, intent(in) :: n
real(kind=dp), intent(in) :: base
Return Value real(kind=dp)(max(n,0))
private pure module function logspace_1_rsp_default(start, end) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in) :: end
Return Value real(kind=sp)(DEFAULT_LOGSPACE_LENGTH)
private pure module function logspace_1_rsp_n(start, end, n) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in) :: end
integer, intent(in) :: n
Return Value real(kind=sp)(max(n,0))
private pure module function logspace_1_rsp_n_cbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in) :: end
integer, intent(in) :: n
complex(kind=sp), intent(in) :: base
Return Value real(kind=sp)(max(n,0))
private pure module function logspace_1_rsp_n_ibase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in) :: end
integer, intent(in) :: n
integer, intent(in) :: base
Return Value real(kind=sp)(max(n,0))
private pure module function logspace_1_rsp_n_rbase(start, end, n, base) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: start
real(kind=sp), intent(in) :: end
integer, intent(in) :: n
real(kind=sp), intent(in) :: base
Return Value real(kind=sp)(max(n,0))
Call graph
test_logspace_dp calls logspace
test_logspace_default calls logspace
test_logspace_base_2 calls logspace
test_logspace_base_2_cmplx_start calls logspace
test_logspace_base_i_int_start calls logspace
test_logspace_sp calls logspace