mean – Fortran-lang/stdlib
mean Interface
882 statements
Source File
public interface mean
Called by
Contents
Functions
mean_1_cdp_cdp mean_1_cqp_cqp mean_1_csp_csp mean_1_iint16_dp mean_1_iint32_dp mean_1_iint64_dp mean_1_iint8_dp mean_1_rdp_rdp mean_1_rqp_rqp mean_1_rsp_rsp mean_2_cdp_cdp mean_2_cqp_cqp mean_2_csp_csp mean_2_iint16_dp mean_2_iint32_dp mean_2_iint64_dp mean_2_iint8_dp mean_2_rdp_rdp mean_2_rqp_rqp mean_2_rsp_rsp mean_3_cdp_cdp mean_3_cqp_cqp mean_3_csp_csp mean_3_iint16_dp mean_3_iint32_dp mean_3_iint64_dp mean_3_iint8_dp mean_3_rdp_rdp mean_3_rqp_rqp mean_3_rsp_rsp mean_4_cdp_cdp mean_4_cqp_cqp mean_4_csp_csp mean_4_iint16_dp mean_4_iint32_dp mean_4_iint64_dp mean_4_iint8_dp mean_4_rdp_rdp mean_4_rqp_rqp mean_4_rsp_rsp mean_all_1_cdp_cdp mean_all_1_cqp_cqp mean_all_1_csp_csp mean_all_1_iint16_dp mean_all_1_iint32_dp mean_all_1_iint64_dp mean_all_1_iint8_dp mean_all_1_rdp_rdp mean_all_1_rqp_rqp mean_all_1_rsp_rsp mean_all_2_cdp_cdp mean_all_2_cqp_cqp mean_all_2_csp_csp mean_all_2_iint16_dp mean_all_2_iint32_dp mean_all_2_iint64_dp mean_all_2_iint8_dp mean_all_2_rdp_rdp mean_all_2_rqp_rqp mean_all_2_rsp_rsp mean_all_3_cdp_cdp mean_all_3_cqp_cqp mean_all_3_csp_csp mean_all_3_iint16_dp mean_all_3_iint32_dp mean_all_3_iint64_dp mean_all_3_iint8_dp mean_all_3_rdp_rdp mean_all_3_rqp_rqp mean_all_3_rsp_rsp mean_all_4_cdp_cdp mean_all_4_cqp_cqp mean_all_4_csp_csp mean_all_4_iint16_dp mean_all_4_iint32_dp mean_all_4_iint64_dp mean_all_4_iint8_dp mean_all_4_rdp_rdp mean_all_4_rqp_rqp mean_all_4_rsp_rsp mean_mask_1_cdp_cdp mean_mask_1_cqp_cqp mean_mask_1_csp_csp mean_mask_1_iint16_dp mean_mask_1_iint32_dp mean_mask_1_iint64_dp mean_mask_1_iint8_dp mean_mask_1_rdp_rdp mean_mask_1_rqp_rqp mean_mask_1_rsp_rsp mean_mask_2_cdp_cdp mean_mask_2_cqp_cqp mean_mask_2_csp_csp mean_mask_2_iint16_dp mean_mask_2_iint32_dp mean_mask_2_iint64_dp mean_mask_2_iint8_dp mean_mask_2_rdp_rdp mean_mask_2_rqp_rqp mean_mask_2_rsp_rsp mean_mask_3_cdp_cdp mean_mask_3_cqp_cqp mean_mask_3_csp_csp mean_mask_3_iint16_dp mean_mask_3_iint32_dp mean_mask_3_iint64_dp mean_mask_3_iint8_dp mean_mask_3_rdp_rdp mean_mask_3_rqp_rqp mean_mask_3_rsp_rsp mean_mask_4_cdp_cdp mean_mask_4_cqp_cqp mean_mask_4_csp_csp mean_mask_4_iint16_dp mean_mask_4_iint32_dp mean_mask_4_iint64_dp mean_mask_4_iint8_dp mean_mask_4_rdp_rdp mean_mask_4_rqp_rqp mean_mask_4_rsp_rsp mean_mask_all_1_cdp_cdp mean_mask_all_1_cqp_cqp mean_mask_all_1_csp_csp mean_mask_all_1_iint16_dp mean_mask_all_1_iint32_dp mean_mask_all_1_iint64_dp mean_mask_all_1_iint8_dp mean_mask_all_1_rdp_rdp mean_mask_all_1_rqp_rqp mean_mask_all_1_rsp_rsp mean_mask_all_2_cdp_cdp mean_mask_all_2_cqp_cqp mean_mask_all_2_csp_csp mean_mask_all_2_iint16_dp mean_mask_all_2_iint32_dp mean_mask_all_2_iint64_dp mean_mask_all_2_iint8_dp mean_mask_all_2_rdp_rdp mean_mask_all_2_rqp_rqp mean_mask_all_2_rsp_rsp mean_mask_all_3_cdp_cdp mean_mask_all_3_cqp_cqp mean_mask_all_3_csp_csp mean_mask_all_3_iint16_dp mean_mask_all_3_iint32_dp mean_mask_all_3_iint64_dp mean_mask_all_3_iint8_dp mean_mask_all_3_rdp_rdp mean_mask_all_3_rqp_rqp mean_mask_all_3_rsp_rsp mean_mask_all_4_cdp_cdp mean_mask_all_4_cqp_cqp mean_mask_all_4_csp_csp mean_mask_all_4_iint16_dp mean_mask_all_4_iint32_dp mean_mask_all_4_iint64_dp mean_mask_all_4_iint8_dp mean_mask_all_4_rdp_rdp mean_mask_all_4_rqp_rqp mean_mask_all_4_rsp_rsp
Functions
public function mean_1_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
public function mean_1_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
public function mean_1_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
public function mean_1_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_1_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_1_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_1_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_1_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_1_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=qp)
public function mean_1_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=sp)
public function mean_2_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_2_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_3_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_4_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_all_1_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
public function mean_all_1_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
public function mean_all_1_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
public function mean_all_1_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_1_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_1_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_1_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_1_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_1_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=qp)
public function mean_all_1_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
logical, intent(in), optional :: mask
Return Value real(kind=sp)
public function mean_all_2_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
public function mean_all_2_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
public function mean_all_2_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
public function mean_all_2_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_2_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_2_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_2_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_2_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_2_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=qp)
public function mean_all_2_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
Return Value real(kind=sp)
public function mean_all_3_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
public function mean_all_3_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
public function mean_all_3_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
public function mean_all_3_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_3_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_3_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_3_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_3_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_3_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=qp)
public function mean_all_3_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=sp)
public function mean_all_4_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=dp)
public function mean_all_4_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=qp)
public function mean_all_4_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value complex(kind=sp)
public function mean_all_4_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_4_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_4_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_4_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_4_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=dp)
public function mean_all_4_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=qp)
public function mean_all_4_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
Return Value real(kind=sp)
public function mean_mask_1_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value complex(kind=dp)
public function mean_mask_1_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value complex(kind=qp)
public function mean_mask_1_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value complex(kind=sp)
public function mean_mask_1_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_1_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_1_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_1_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_1_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_1_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=qp)
public function mean_mask_1_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
Return Value real(kind=sp)
public function mean_mask_2_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_2_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_3_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_cdp_cdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_cqp_cqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_csp_csp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_iint16_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_iint32_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_iint64_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_iint8_dp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_rdp_rdp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_rqp_rqp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_4_rsp_rsp(x, dim, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function mean_mask_all_1_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value complex(kind=dp)
public function mean_mask_all_1_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value complex(kind=qp)
public function mean_mask_all_1_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value complex(kind=sp)
public function mean_mask_all_1_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_all_1_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_all_1_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_all_1_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_all_1_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=dp)
public function mean_mask_all_1_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=qp)
public function mean_mask_all_1_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
Return Value real(kind=sp)
public function mean_mask_all_2_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value complex(kind=dp)
public function mean_mask_all_2_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value complex(kind=qp)
public function mean_mask_all_2_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value complex(kind=sp)
public function mean_mask_all_2_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp)
public function mean_mask_all_2_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp)
public function mean_mask_all_2_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp)
public function mean_mask_all_2_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp)
public function mean_mask_all_2_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=dp)
public function mean_mask_all_2_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=qp)
public function mean_mask_all_2_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
Return Value real(kind=sp)
public function mean_mask_all_3_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=dp)
public function mean_mask_all_3_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=qp)
public function mean_mask_all_3_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value complex(kind=sp)
public function mean_mask_all_3_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_3_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_3_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_3_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_3_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_3_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=qp)
public function mean_mask_all_3_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
Return Value real(kind=sp)
public function mean_mask_all_4_cdp_cdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=dp)
public function mean_mask_all_4_cqp_cqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=qp)
public function mean_mask_all_4_csp_csp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value complex(kind=sp)
public function mean_mask_all_4_iint16_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_4_iint32_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_4_iint64_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_4_iint8_dp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_4_rdp_rdp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=dp)
public function mean_mask_all_4_rqp_rqp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=qp)
public function mean_mask_all_4_rsp_rsp(x, mask) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
Return Value real(kind=sp)
Call graph
moment_mask_all_1_cqp_cqp calls mean
moment_mask_1_cqp_cqp calls mean
moment_all_2_rqp_rqp calls mean
moment_mask_all_2_cdp_cdp calls mean
moment_4_iint64_dp calls mean
cov_mask_2_rsp_rsp calls mean
moment_mask_all_3_iint8_dp calls mean
moment_mask_all_4_iint64_dp calls mean
moment_mask_1_csp_csp calls mean
moment_mask_all_4_iint32_dp calls mean
moment_mask_3_rdp_rdp calls mean
moment_mask_all_3_iint16_dp calls mean
moment_1_iint16_dp calls mean
moment_3_csp_csp calls mean
moment_mask_3_rqp_rqp calls mean
moment_4_cdp_cdp calls mean
moment_mask_all_4_cdp_cdp calls mean
moment_all_3_iint8_dp calls mean
moment_2_cqp_cqp calls mean
moment_all_2_iint16_dp calls mean
moment_mask_3_rsp_rsp calls mean
moment_2_rsp_rsp calls mean
moment_4_iint8_dp calls mean
moment_mask_all_1_iint64_dp calls mean
moment_2_iint64_dp calls mean
moment_mask_all_1_iint16_dp calls mean
moment_mask_3_iint16_dp calls mean
moment_all_2_cqp_cqp calls mean
moment_mask_all_3_rsp_rsp calls mean
moment_mask_all_3_csp_csp calls mean
moment_mask_2_iint32_dp calls mean
moment_all_3_rqp_rqp calls mean
moment_all_3_csp_csp calls mean
moment_mask_1_iint64_dp calls mean
moment_mask_2_cqp_cqp calls mean
moment_mask_all_1_iint8_dp calls mean
moment_1_rsp_rsp calls mean
moment_3_rqp_rqp calls mean
moment_mask_all_2_iint32_dp calls mean
moment_mask_1_iint8_dp calls mean
moment_1_cdp_cdp calls mean
moment_mask_4_rqp_rqp calls mean
cov_2_rdp_rdp calls mean
moment_1_iint64_dp calls mean
moment_3_iint8_dp calls mean
moment_4_rdp_rdp calls mean
moment_mask_all_2_rqp_rqp calls mean
moment_3_iint16_dp calls mean
moment_all_1_rdp_rdp calls mean
moment_mask_all_1_rdp_rdp calls mean
moment_3_iint32_dp calls mean
moment_mask_2_iint16_dp calls mean
moment_mask_all_3_cqp_cqp calls mean
cov_2_iint64_dp calls mean
moment_mask_all_1_cdp_cdp calls mean
moment_all_4_iint64_dp calls mean
moment_all_1_csp_csp calls mean
cov_2_iint16_dp calls mean
moment_mask_4_iint16_dp calls mean
moment_all_3_iint32_dp calls mean
moment_3_rdp_rdp calls mean
cov_mask_2_iint8_dp calls mean
moment_mask_3_iint32_dp calls mean
cov_2_csp_csp calls mean
moment_all_2_rdp_rdp calls mean
moment_all_2_csp_csp calls mean
moment_all_3_rdp_rdp calls mean
cov_mask_2_iint64_dp calls mean
moment_1_cqp_cqp calls mean
moment_2_iint16_dp calls mean
moment_2_iint32_dp calls mean
moment_2_cdp_cdp calls mean
moment_all_1_rqp_rqp calls mean
moment_all_4_cqp_cqp calls mean
moment_mask_3_iint64_dp calls mean
moment_all_1_cqp_cqp calls mean
moment_mask_all_4_rqp_rqp calls mean
moment_mask_all_4_rdp_rdp calls mean
moment_4_cqp_cqp calls mean
moment_all_1_iint8_dp calls mean
moment_all_2_iint64_dp calls mean
moment_mask_2_iint8_dp calls mean
moment_mask_4_cdp_cdp calls mean
moment_mask_4_iint64_dp calls mean
moment_4_csp_csp calls mean
moment_2_csp_csp calls mean
moment_mask_all_2_rdp_rdp calls mean
moment_mask_1_iint32_dp calls mean
moment_2_rdp_rdp calls mean
moment_all_2_cdp_cdp calls mean
moment_mask_4_rsp_rsp calls mean
moment_mask_2_rqp_rqp calls mean
moment_all_2_rsp_rsp calls mean
cov_mask_2_iint32_dp calls mean
moment_mask_all_4_rsp_rsp calls mean
cov_2_iint8_dp calls mean
moment_mask_1_rqp_rqp calls mean
moment_mask_3_cdp_cdp calls mean
moment_mask_4_rdp_rdp calls mean
moment_4_iint16_dp calls mean
moment_all_3_cqp_cqp calls mean
moment_mask_1_rsp_rsp calls mean
moment_all_3_iint64_dp calls mean
moment_2_iint8_dp calls mean
moment_mask_all_4_cqp_cqp calls mean
moment_mask_all_1_iint32_dp calls mean
moment_all_4_rsp_rsp calls mean
moment_mask_all_3_iint64_dp calls mean
moment_mask_all_3_rdp_rdp calls mean
moment_mask_4_cqp_cqp calls mean
cov_mask_2_csp_csp calls mean
moment_all_1_iint16_dp calls mean
cov_2_iint32_dp calls mean
moment_mask_all_1_csp_csp calls mean
moment_3_rsp_rsp calls mean
moment_mask_2_rdp_rdp calls mean
moment_mask_3_cqp_cqp calls mean
moment_mask_all_1_rqp_rqp calls mean
moment_mask_1_iint16_dp calls mean
moment_4_rsp_rsp calls mean
moment_1_iint32_dp calls mean
moment_all_1_rsp_rsp calls mean
cov_2_cdp_cdp calls mean
moment_1_iint8_dp calls mean
moment_mask_all_4_csp_csp calls mean
moment_mask_all_3_rqp_rqp calls mean
cov_mask_2_rdp_rdp calls mean
moment_mask_all_2_cqp_cqp calls mean
moment_mask_all_4_iint16_dp calls mean
moment_1_rqp_rqp calls mean
moment_all_1_cdp_cdp calls mean
moment_mask_1_rdp_rdp calls mean
moment_all_1_iint64_dp calls mean
moment_mask_2_csp_csp calls mean
cov_2_rsp_rsp calls mean
moment_all_3_cdp_cdp calls mean
moment_mask_all_2_csp_csp calls mean
moment_mask_2_iint64_dp calls mean
cov_2_cqp_cqp calls mean
moment_2_rqp_rqp calls mean
moment_3_iint64_dp calls mean
cov_mask_2_rqp_rqp calls mean
moment_mask_3_csp_csp calls mean
moment_mask_all_2_iint16_dp calls mean
moment_mask_all_2_iint8_dp calls mean
cov_mask_2_iint16_dp calls mean
moment_mask_4_iint32_dp calls mean
moment_all_2_iint8_dp calls mean
moment_4_rqp_rqp calls mean
moment_mask_3_iint8_dp calls mean
moment_mask_4_csp_csp calls mean
moment_all_3_rsp_rsp calls mean
cov_mask_2_cqp_cqp calls mean
moment_3_cqp_cqp calls mean
moment_4_iint32_dp calls mean
moment_all_4_iint32_dp calls mean
moment_all_4_rqp_rqp calls mean
moment_all_4_rdp_rdp calls mean
moment_mask_all_1_rsp_rsp calls mean
moment_all_4_cdp_cdp calls mean
moment_mask_all_2_rsp_rsp calls mean
moment_1_csp_csp calls mean
moment_mask_all_3_cdp_cdp calls mean
moment_3_cdp_cdp calls mean
moment_all_4_iint8_dp calls mean
moment_mask_all_2_iint64_dp calls mean
moment_all_4_iint16_dp calls mean
moment_all_2_iint32_dp calls mean
cov_mask_2_cdp_cdp calls mean
moment_all_4_csp_csp calls mean
cov_2_rqp_rqp calls mean
moment_mask_1_cdp_cdp calls mean
moment_1_rdp_rdp calls mean
moment_all_3_iint16_dp calls mean
moment_mask_2_cdp_cdp calls mean
moment_mask_4_iint8_dp calls mean
moment_all_1_iint32_dp calls mean
moment_mask_all_4_iint8_dp calls mean
moment_mask_2_rsp_rsp calls mean
moment_mask_all_3_iint32_dp calls mean