optval – Fortran-lang/stdlib
optval Interface
14 statements
Source File
public interface optval
Calls
Called by
check w optval
w
cov_1_cdp_cdp w
w
cov_1_cqp_cqp w
w
cov_1_csp_csp w
w
cov_1_iint16_dp w
w
cov_1_iint32_dp w
w
cov_1_iint64_dp w
w
cov_1_iint8_dp w
w
cov_1_rdp_rdp w
w
cov_1_rqp_rqp w
w
cov_1_rsp_rsp w
w
cov_2_cdp_cdp w
w
cov_2_cqp_cqp w
w
cov_2_csp_csp w
w
cov_2_iint16_dp w
w
cov_2_iint32_dp w
w
cov_2_iint64_dp w
w
cov_2_iint8_dp w
w
cov_2_rdp_rdp w
w
cov_2_rqp_rqp w
w
cov_2_rsp_rsp w
w
cov_mask_1_cdp_cdp w
w
cov_mask_1_cqp_cqp w
w
cov_mask_1_csp_csp w
w
cov_mask_1_iint16_dp w
w
cov_mask_1_iint32_dp w
w
cov_mask_1_iint64_dp w
w
cov_mask_1_iint8_dp w
w
cov_mask_1_rdp_rdp w
w
cov_mask_1_rqp_rqp w
w
cov_mask_1_rsp_rsp w
w
cov_mask_2_cdp_cdp w
w
cov_mask_2_cqp_cqp w
w
cov_mask_2_csp_csp w
w
cov_mask_2_iint16_dp w
w
cov_mask_2_iint32_dp w
w
cov_mask_2_iint64_dp w
w
cov_mask_2_iint8_dp w
w
cov_mask_2_rdp_rdp w
w
cov_mask_2_rqp_rqp w
w
cov_mask_2_rsp_rsp w
w
mean_1_cdp_cdp w
w
mean_1_cqp_cqp w
w
mean_1_csp_csp w
w
mean_1_iint16_dp w
w
mean_1_iint32_dp w
w
mean_1_iint64_dp w
w
mean_1_iint8_dp w
w
mean_1_rdp_rdp w
w
mean_1_rqp_rqp w
w
mean_1_rsp_rsp w
w
mean_2_cdp_cdp w
w
mean_2_cqp_cqp w
w
mean_2_csp_csp w
w
mean_2_iint16_dp w
w
mean_2_iint32_dp w
w
mean_2_iint64_dp w
w
mean_2_iint8_dp w
w
mean_2_rdp_rdp w
w
mean_2_rqp_rqp w
w
mean_2_rsp_rsp w
w
mean_3_cdp_cdp w
w
mean_3_cqp_cqp w
w
mean_3_csp_csp w
w
mean_3_iint16_dp w
w
mean_3_iint32_dp w
w
mean_3_iint64_dp w
w
mean_3_iint8_dp w
w
mean_3_rdp_rdp w
w
mean_3_rqp_rqp w
w
mean_3_rsp_rsp w
w
mean_4_cdp_cdp w
w
mean_4_cqp_cqp w
w
mean_4_csp_csp w
w
mean_4_iint16_dp w
w
mean_4_iint32_dp w
w
mean_4_iint64_dp w
w
mean_4_iint8_dp w
w
mean_4_rdp_rdp w
w
mean_4_rqp_rqp w
w
mean_4_rsp_rsp w
w
mean_all_1_cdp_cdp w
w
mean_all_1_cqp_cqp w
w
mean_all_1_csp_csp w
w
mean_all_1_iint16_dp w
w
mean_all_1_iint32_dp w
w
mean_all_1_iint64_dp w
w
mean_all_1_iint8_dp w
w
mean_all_1_rdp_rdp w
w
mean_all_1_rqp_rqp w
w
mean_all_1_rsp_rsp w
w
mean_all_2_cdp_cdp w
w
mean_all_2_cqp_cqp w
w
mean_all_2_csp_csp w
w
mean_all_2_iint16_dp w
w
mean_all_2_iint32_dp w
w
mean_all_2_iint64_dp w
w
mean_all_2_iint8_dp w
w
mean_all_2_rdp_rdp w
w
mean_all_2_rqp_rqp w
w
mean_all_2_rsp_rsp w
w
mean_all_3_cdp_cdp w
w
mean_all_3_cqp_cqp w
w
mean_all_3_csp_csp w
w
mean_all_3_iint16_dp w
w
mean_all_3_iint32_dp w
w
mean_all_3_iint64_dp w
w
mean_all_3_iint8_dp w
w
mean_all_3_rdp_rdp w
w
mean_all_3_rqp_rqp w
w
mean_all_3_rsp_rsp w
w
mean_all_4_cdp_cdp w
w
mean_all_4_cqp_cqp w
w
mean_all_4_csp_csp w
w
mean_all_4_iint16_dp w
w
mean_all_4_iint32_dp w
w
mean_all_4_iint64_dp w
w
mean_all_4_iint8_dp w
w
mean_all_4_rdp_rdp w
w
mean_all_4_rqp_rqp w
w
mean_all_4_rsp_rsp w
w
moment_1_cdp_cdp w
w
moment_1_cqp_cqp w
w
moment_1_csp_csp w
w
moment_1_iint16_dp w
w
moment_1_iint32_dp w
w
moment_1_iint64_dp w
w
moment_1_iint8_dp w
w
moment_1_rdp_rdp w
w
moment_1_rqp_rqp w
w
moment_1_rsp_rsp w
w
moment_2_cdp_cdp w
w
moment_2_cqp_cqp w
w
moment_2_csp_csp w
w
moment_2_iint16_dp w
w
moment_2_iint32_dp w
w
moment_2_iint64_dp w
w
moment_2_iint8_dp w
w
moment_2_rdp_rdp w
w
moment_2_rqp_rqp w
w
moment_2_rsp_rsp w
w
moment_3_cdp_cdp w
w
moment_3_cqp_cqp w
w
moment_3_csp_csp w
w
moment_3_iint16_dp w
w
moment_3_iint32_dp w
w
moment_3_iint64_dp w
w
moment_3_iint8_dp w
w
moment_3_rdp_rdp w
w
moment_3_rqp_rqp w
w
moment_3_rsp_rsp w
w
moment_4_cdp_cdp w
w
moment_4_cqp_cqp w
w
moment_4_csp_csp w
w
moment_4_iint16_dp w
w
moment_4_iint32_dp w
w
moment_4_iint64_dp w
w
moment_4_iint8_dp w
w
moment_4_rdp_rdp w
w
moment_4_rqp_rqp w
w
moment_4_rsp_rsp w
w
moment_all_1_cdp_cdp w
w
moment_all_1_cqp_cqp w
w
moment_all_1_csp_csp w
w
moment_all_1_iint16_dp w
w
moment_all_1_iint32_dp w
w
moment_all_1_iint64_dp w
w
moment_all_1_iint8_dp w
w
moment_all_1_rdp_rdp w
w
moment_all_1_rqp_rqp w
w
moment_all_1_rsp_rsp w
w
moment_all_2_cdp_cdp w
w
moment_all_2_cqp_cqp w
w
moment_all_2_csp_csp w
w
moment_all_2_iint16_dp w
w
moment_all_2_iint32_dp w
w
moment_all_2_iint64_dp w
w
moment_all_2_iint8_dp w
w
moment_all_2_rdp_rdp w
w
moment_all_2_rqp_rqp w
w
moment_all_2_rsp_rsp w
w
moment_all_3_cdp_cdp w
w
moment_all_3_cqp_cqp w
w
moment_all_3_csp_csp w
w
moment_all_3_iint16_dp w
w
moment_all_3_iint32_dp w
w
moment_all_3_iint64_dp w
w
moment_all_3_iint8_dp w
w
moment_all_3_rdp_rdp w
w
moment_all_3_rqp_rqp w
w
moment_all_3_rsp_rsp w
w
moment_all_4_cdp_cdp w
w
moment_all_4_cqp_cqp w
w
moment_all_4_csp_csp w
w
moment_all_4_iint16_dp w
w
moment_all_4_iint32_dp w
w
moment_all_4_iint64_dp w
w
moment_all_4_iint8_dp w
w
moment_all_4_rdp_rdp w
w
moment_all_4_rqp_rqp w
w
moment_all_4_rsp_rsp w
w
moment_scalar_2_cdp_cdp w
w
moment_scalar_2_cqp_cqp w
w
moment_scalar_2_csp_csp w
w
moment_scalar_2_iint16_dp w
w
moment_scalar_2_iint32_dp w
w
moment_scalar_2_iint64_dp w
w
moment_scalar_2_iint8_dp w
w
moment_scalar_2_rdp_rdp w
w
moment_scalar_2_rqp_rqp w
w
moment_scalar_2_rsp_rsp w
w
moment_scalar_3_cdp_cdp w
w
moment_scalar_3_cqp_cqp w
w
moment_scalar_3_csp_csp w
w
moment_scalar_3_iint16_dp w
w
moment_scalar_3_iint32_dp w
w
moment_scalar_3_iint64_dp w
w
moment_scalar_3_iint8_dp w
w
moment_scalar_3_rdp_rdp w
w
moment_scalar_3_rqp_rqp w
w
moment_scalar_3_rsp_rsp w
w
moment_scalar_4_cdp_cdp w
w
moment_scalar_4_cqp_cqp w
w
moment_scalar_4_csp_csp w
w
moment_scalar_4_iint16_dp w
w
moment_scalar_4_iint32_dp w
w
moment_scalar_4_iint64_dp w
w
moment_scalar_4_iint8_dp w
w
moment_scalar_4_rdp_rdp w
w
moment_scalar_4_rqp_rqp w
w
moment_scalar_4_rsp_rsp w
w
open w
w
var_1_cdp_cdp w
w
var_1_cqp_cqp w
w
var_1_csp_csp w
w
var_1_iint16_dp w
w
var_1_iint32_dp w
w
var_1_iint64_dp w
w
var_1_iint8_dp w
w
var_1_rdp_rdp w
w
var_1_rqp_rqp w
w
var_1_rsp_rsp w
w
var_2_cdp_cdp w
w
var_2_cqp_cqp w
w
var_2_csp_csp w
w
var_2_iint16_dp w
w
var_2_iint32_dp w
w
var_2_iint64_dp w
w
var_2_iint8_dp w
w
var_2_rdp_rdp w
w
var_2_rqp_rqp w
w
var_2_rsp_rsp w
w
var_3_cdp_cdp w
w
var_3_cqp_cqp w
w
var_3_csp_csp w
w
var_3_iint16_dp w
w
var_3_iint32_dp w
w
var_3_iint64_dp w
w
var_3_iint8_dp w
w
var_3_rdp_rdp w
w
var_3_rqp_rqp w
w
var_3_rsp_rsp w
w
var_4_cdp_cdp w
w
var_4_cqp_cqp w
w
var_4_csp_csp w
w
var_4_iint16_dp w
w
var_4_iint32_dp w
w
var_4_iint64_dp w
w
var_4_iint8_dp w
w
var_4_rdp_rdp w
w
var_4_rqp_rqp w
w
var_4_rsp_rsp w
w
var_all_1_cdp_cdp w
w
var_all_1_cqp_cqp w
w
var_all_1_csp_csp w
w
var_all_1_iint16_dp w
w
var_all_1_iint32_dp w
w
var_all_1_iint64_dp w
w
var_all_1_iint8_dp w
w
var_all_1_rdp_rdp w
w
var_all_1_rqp_rqp w
w
var_all_1_rsp_rsp w
w
var_all_2_cdp_cdp w
w
var_all_2_cqp_cqp w
w
var_all_2_csp_csp w
w
var_all_2_iint16_dp w
w
var_all_2_iint32_dp w
w
var_all_2_iint64_dp w
w
var_all_2_iint8_dp w
w
var_all_2_rdp_rdp w
w
var_all_2_rqp_rqp w
w
var_all_2_rsp_rsp w
w
var_all_3_cdp_cdp w
w
var_all_3_cqp_cqp w
w
var_all_3_csp_csp w
w
var_all_3_iint16_dp w
w
var_all_3_iint32_dp w
w
var_all_3_iint64_dp w
w
var_all_3_iint8_dp w
w
var_all_3_rdp_rdp w
w
var_all_3_rqp_rqp w
w
var_all_3_rsp_rsp w
w
var_all_4_cdp_cdp w
w
var_all_4_cqp_cqp w
w
var_all_4_csp_csp w
w
var_all_4_iint16_dp w
w
var_all_4_iint32_dp w
w
var_all_4_iint64_dp w
w
var_all_4_iint8_dp w
w
var_all_4_rdp_rdp w
w
var_all_4_rqp_rqp w
w
var_all_4_rsp_rsp w
w
var_mask_1_cdp_cdp w
w
var_mask_1_cqp_cqp w
w
var_mask_1_csp_csp w
w
var_mask_1_iint16_dp w
w
var_mask_1_iint32_dp w
w
var_mask_1_iint64_dp w
w
var_mask_1_iint8_dp w
w
var_mask_1_rdp_rdp w
w
var_mask_1_rqp_rqp w
w
var_mask_1_rsp_rsp w
w
var_mask_2_cdp_cdp w
w
var_mask_2_cqp_cqp w
w
var_mask_2_csp_csp w
w
var_mask_2_iint16_dp w
w
var_mask_2_iint32_dp w
w
var_mask_2_iint64_dp w
w
var_mask_2_iint8_dp w
w
var_mask_2_rdp_rdp w
w
var_mask_2_rqp_rqp w
w
var_mask_2_rsp_rsp w
w
var_mask_3_cdp_cdp w
w
var_mask_3_cqp_cqp w
w
var_mask_3_csp_csp w
w
var_mask_3_iint16_dp w
w
var_mask_3_iint32_dp w
w
var_mask_3_iint64_dp w
w
var_mask_3_iint8_dp w
w
var_mask_3_rdp_rdp w
w
var_mask_3_rqp_rqp w
w
var_mask_3_rsp_rsp w
w
var_mask_4_cdp_cdp w
w
var_mask_4_cqp_cqp w
w
var_mask_4_csp_csp w
w
var_mask_4_iint16_dp w
w
var_mask_4_iint32_dp w
w
var_mask_4_iint64_dp w
w
var_mask_4_iint8_dp w
w
var_mask_4_rdp_rdp w
w
var_mask_4_rqp_rqp w
w
var_mask_4_rsp_rsp w
w
var_mask_all_1_cdp_cdp w
w
var_mask_all_1_cqp_cqp w
w
var_mask_all_1_csp_csp w
w
var_mask_all_1_iint16_dp w
w
var_mask_all_1_iint32_dp w
w
var_mask_all_1_iint64_dp w
w
var_mask_all_1_iint8_dp w
w
var_mask_all_1_rdp_rdp w
w
var_mask_all_1_rqp_rqp w
w
var_mask_all_1_rsp_rsp w
w
var_mask_all_2_cdp_cdp w
w
var_mask_all_2_cqp_cqp w
w
var_mask_all_2_csp_csp w
w
var_mask_all_2_iint16_dp w
w
var_mask_all_2_iint32_dp w
w
var_mask_all_2_iint64_dp w
w
var_mask_all_2_iint8_dp w
w
var_mask_all_2_rdp_rdp w
w
var_mask_all_2_rqp_rqp w
w
var_mask_all_2_rsp_rsp w
w
var_mask_all_3_cdp_cdp w
w
var_mask_all_3_cqp_cqp w
w
var_mask_all_3_csp_csp w
w
var_mask_all_3_iint16_dp w
w
var_mask_all_3_iint32_dp w
w
var_mask_all_3_iint64_dp w
w
var_mask_all_3_iint8_dp w
w
var_mask_all_3_rdp_rdp w
w
var_mask_all_3_rqp_rqp w
w
var_mask_all_3_rsp_rsp w
w
var_mask_all_4_cdp_cdp w
w
var_mask_all_4_cqp_cqp w
w
var_mask_all_4_csp_csp w
w
var_mask_all_4_iint16_dp w
w
var_mask_all_4_iint32_dp w
w
var_mask_all_4_iint64_dp w
w
var_mask_all_4_iint8_dp w
w
var_mask_all_4_rdp_rdp w
w
var_mask_all_4_rqp_rqp w
w
var_mask_all_4_rsp_rsp w
w
Contents
Module Procedures
optval_rsp optval_rdp optval_rqp optval_iint8 optval_iint16 optval_iint32 optval_iint64 optval_csp optval_cdp optval_cqp optval_ll1 optval_character
Module Procedures
private pure elemental function optval_rsp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in), optional :: x
real(kind=sp), intent(in) :: default
Return Value real(kind=sp)
private pure elemental function optval_rdp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), optional :: x
real(kind=dp), intent(in) :: default
Return Value real(kind=dp)
private pure elemental function optval_rqp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in), optional :: x
real(kind=qp), intent(in) :: default
Return Value real(kind=qp)
private pure elemental function optval_iint8(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in), optional :: x
integer(kind=int8), intent(in) :: default
Return Value integer(kind=int8)
private pure elemental function optval_iint16(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in), optional :: x
integer(kind=int16), intent(in) :: default
Return Value integer(kind=int16)
private pure elemental function optval_iint32(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in), optional :: x
integer(kind=int32), intent(in) :: default
Return Value integer(kind=int32)
private pure elemental function optval_iint64(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), optional :: x
integer(kind=int64), intent(in) :: default
Return Value integer(kind=int64)
private pure elemental function optval_csp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in), optional :: x
complex(kind=sp), intent(in) :: default
Return Value complex(kind=sp)
private pure elemental function optval_cdp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in), optional :: x
complex(kind=dp), intent(in) :: default
Return Value complex(kind=dp)
private pure elemental function optval_cqp(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in), optional :: x
complex(kind=qp), intent(in) :: default
Return Value complex(kind=qp)
private pure elemental function optval_ll1(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: x
logical, intent(in) :: default
Return Value logical
private pure function optval_character(x, default) result(y)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: x
character(len=*), intent(in) :: default
Return Value character(len=:), allocatable
Call graph
optval calls optval_rqp, optval_csp, optval_iint16, optval_character, optval_rdp, optval_iint64, optval_cdp, optval_ll1, optval_rsp, optval_iint8, optval_iint32, optval_cqp