pdf_normal – Fortran-lang/stdlib
pdf_normal Interface
experimental
6 statements
Source File
public interface pdf_normal
Normal Distribution Probability Density Function (Specification)
Called by
Contents
Module Procedures
pdf_norm_rsp pdf_norm_rdp pdf_norm_csp pdf_norm_cdp
Module Procedures
private impure elemental function pdf_norm_rsp(x, loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x
real(kind=sp), intent(in) :: loc
real(kind=sp), intent(in) :: scale
Return Value real(kind=sp)
private impure elemental function pdf_norm_rdp(x, loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
real(kind=dp), intent(in) :: loc
real(kind=dp), intent(in) :: scale
Return Value real(kind=dp)
private impure elemental function pdf_norm_csp(x, loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x
complex(kind=sp), intent(in) :: loc
complex(kind=sp), intent(in) :: scale
Return Value real(kind=sp)
private impure elemental function pdf_norm_cdp(x, loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x
complex(kind=dp), intent(in) :: loc
complex(kind=dp), intent(in) :: scale
Return Value real(kind=dp)
Call graph
test_nor_pdf_rdp calls pdf_normal
test_nor_pdf_cdp calls pdf_normal
test_nor_pdf_rsp calls pdf_normal
test_nor_pdf_csp calls pdf_normal
test_distribution_normal calls test_nor_pdf_rdp, test_nor_pdf_cdp, test_nor_pdf_rsp, test_nor_pdf_csp