rvs_exp – Fortran-lang/stdlib
rvs_exp Interface
11 statements
Source File
public interface rvs_exp
Version experimental
Exponential Distribution Random Variates (Specification)
Called by
Contents
Module Procedures
rvs_exp_0_rsp rvs_exp_rsp rvs_exp_rdp rvs_exp_csp rvs_exp_cdp rvs_exp_array_rsp rvs_exp_array_rdp rvs_exp_array_csp rvs_exp_array_cdp
Module Procedures
private function rvs_exp_0_rsp() result(res)
Arguments
None
Return Value real(kind=sp)
private function rvs_exp_rsp(lambda) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: lambda
Return Value real(kind=sp)
private function rvs_exp_rdp(lambda) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lambda
Return Value real(kind=dp)
private function rvs_exp_csp(lambda) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: lambda
Return Value complex(kind=sp)
private function rvs_exp_cdp(lambda) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: lambda
Return Value complex(kind=dp)
private function rvs_exp_array_rsp(lambda, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: lambda
integer, intent(in) :: array_size
Return Value real(kind=sp)(array_size)
private function rvs_exp_array_rdp(lambda, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lambda
integer, intent(in) :: array_size
Return Value real(kind=dp)(array_size)
private function rvs_exp_array_csp(lambda, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: lambda
integer, intent(in) :: array_size
Return Value complex(kind=sp)(array_size)
private function rvs_exp_array_cdp(lambda, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: lambda
integer, intent(in) :: array_size
Return Value complex(kind=dp)(array_size)
Call graph
test_expon_rvs_csp calls rvs_exp
test_expon_pdf_cdp calls rvs_exp
test_expon_rvs_cdp calls rvs_exp
test_exponential_random_generator calls rvs_exp
test_expon_cdf_rsp calls rvs_exp
test_expon_cdf_csp calls rvs_exp
test_expon_cdf_rdp calls rvs_exp
test_expon_cdf_cdp calls rvs_exp
test_expon_rvs_rdp calls rvs_exp
test_expon_pdf_csp calls rvs_exp
test_expon_rvs_rsp calls rvs_exp
test_expon_pdf_rdp calls rvs_exp
test_expon_pdf_rsp calls rvs_exp
test_distribution_expon calls test_expon_rvs_csp, test_expon_pdf_cdp, test_expon_rvs_cdp, test_exponential_random_generator, test_expon_cdf_rsp, test_expon_cdf_csp, test_expon_cdf_rdp, test_expon_cdf_cdp, test_expon_rvs_rdp, test_expon_pdf_csp, test_expon_rvs_rsp, test_expon_pdf_rdp, test_expon_pdf_rsp