rvs_normal – Fortran-lang/stdlib
rvs_normal Interface
experimental
11 statements
Source File
public interface rvs_normal
Normal Distribution Random Variates (Specification)
Called by
Contents
Module Procedures
rvs_norm_0_rsp rvs_norm_rsp rvs_norm_rdp rvs_norm_csp rvs_norm_cdp rvs_norm_array_rsp rvs_norm_array_rdp rvs_norm_array_csp rvs_norm_array_cdp
Module Procedures
private function rvs_norm_0_rsp() result(res)
Arguments
None
Return Value real(kind=sp)
private function rvs_norm_rsp(loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: loc
real(kind=sp), intent(in) :: scale
Return Value real(kind=sp)
private function rvs_norm_rdp(loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: loc
real(kind=dp), intent(in) :: scale
Return Value real(kind=dp)
private function rvs_norm_csp(loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: loc
complex(kind=sp), intent(in) :: scale
Return Value complex(kind=sp)
private function rvs_norm_cdp(loc, scale) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: loc
complex(kind=dp), intent(in) :: scale
Return Value complex(kind=dp)
private function rvs_norm_array_rsp(loc, scale, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: loc
real(kind=sp), intent(in) :: scale
integer, intent(in) :: array_size
Return Value real(kind=sp)(array_size)
private function rvs_norm_array_rdp(loc, scale, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: loc
real(kind=dp), intent(in) :: scale
integer, intent(in) :: array_size
Return Value real(kind=dp)(array_size)
private function rvs_norm_array_csp(loc, scale, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: loc
complex(kind=sp), intent(in) :: scale
integer, intent(in) :: array_size
Return Value complex(kind=sp)(array_size)
private function rvs_norm_array_cdp(loc, scale, array_size) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: loc
complex(kind=dp), intent(in) :: scale
integer, intent(in) :: array_size
Return Value complex(kind=dp)(array_size)
Call graph
test_nor_cdf_cdp calls rvs_normal
test_nor_cdf_csp calls rvs_normal
test_nor_rvs_rsp calls rvs_normal
test_nor_pdf_cdp calls rvs_normal
test_nor_cdf_rsp calls rvs_normal
test_nor_pdf_csp calls rvs_normal
test_nor_pdf_rdp calls rvs_normal
test_nor_rvs_cdp calls rvs_normal
test_nor_cdf_rdp calls rvs_normal
test_nor_pdf_rsp calls rvs_normal
test_nor_rvs_rdp calls rvs_normal
test_normal_random_generator calls rvs_normal
test_nor_rvs_csp calls rvs_normal
test_distribution_normal calls test_nor_cdf_cdp, test_nor_cdf_csp, test_nor_rvs_rsp, test_nor_pdf_cdp, test_nor_cdf_rsp, test_nor_pdf_csp, test_nor_pdf_rdp, test_nor_rvs_cdp, test_nor_cdf_rdp, test_nor_pdf_rsp, test_nor_rvs_rdp, test_normal_random_generator, test_nor_rvs_csp