savetxt – Fortran-lang/stdlib
savetxt Interface
12 statements
Source File
public interface savetxt
Calls
Contents
Module Procedures
savetxt_rsp savetxt_rdp savetxt_rqp savetxt_iint8 savetxt_iint16 savetxt_iint32 savetxt_iint64 savetxt_csp savetxt_cdp savetxt_cqp
Module Procedures
private subroutine savetxt_rsp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=sp), intent(in) :: d(:,:)
private subroutine savetxt_rdp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=dp), intent(in) :: d(:,:)
private subroutine savetxt_rqp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=qp), intent(in) :: d(:,:)
private subroutine savetxt_iint8(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int8), intent(in) :: d(:,:)
private subroutine savetxt_iint16(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int16), intent(in) :: d(:,:)
private subroutine savetxt_iint32(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int32), intent(in) :: d(:,:)
private subroutine savetxt_iint64(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer(kind=int64), intent(in) :: d(:,:)
private subroutine savetxt_csp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=sp), intent(in) :: d(:,:)
private subroutine savetxt_cdp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=dp), intent(in) :: d(:,:)
private subroutine savetxt_cqp(filename, d)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
complex(kind=qp), intent(in) :: d(:,:)
Call graph
savetxt calls savetxt_rdp, savetxt_csp, savetxt_iint16, savetxt_rqp, savetxt_cqp, savetxt_rsp, savetxt_cdp, savetxt_iint8, savetxt_iint64, savetxt_iint32