simps – Fortran-lang/stdlib
simps Interface
experimental
26 statements
Source File
public interface simps
Integrates sampled values using Simpson's rule (Specification)
Called by
Contents
Functions
simps_dx_dp simps_dx_sp simps_x_dp simps_x_sp
Functions
private pure recursive module function simps_dx_dp(y, dx, even) result(integral)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:) :: y
real(kind=dp), intent(in) :: dx
integer, intent(in), optional :: even
Return Value real(kind=dp)
private pure recursive module function simps_dx_sp(y, dx, even) result(integral)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in), dimension(:) :: y
real(kind=sp), intent(in) :: dx
integer, intent(in), optional :: even
Return Value real(kind=sp)
private recursive module function simps_x_dp(y, x, even) result(integral)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:) :: y
real(kind=dp), intent(in), dimension(:) :: x
integer, intent(in), optional :: even
Return Value real(kind=dp)
private recursive module function simps_x_sp(y, x, even) result(integral)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in), dimension(:) :: y
real(kind=sp), intent(in), dimension(:) :: x
integer, intent(in), optional :: even
Return Value real(kind=sp)
Call graph
test_simps_dp calls simps
test_simps_weights_sp calls simps
test_simps_weights_even_dp calls simps
test_simps_six_sp calls simps
test_simps_sp calls simps
test_simps_six_dp calls simps
test_simps_weights_even_sp calls simps
test_simps_weights_dp calls simps
test_simps_zero_sp calls simps
test_simps_even_dp calls simps
test_simps_zero_dp calls simps
test_simps_even_sp calls simps