starts_with – Fortran-lang/stdlib
starts_with Interface
6 statements
Source File
public interface starts_with
Check whether a string starts with substring or not
Version: experimental
Called by
Contents
Module Procedures
starts_with_string_string starts_with_string_char starts_with_char_string starts_with_char_char
Module Procedures
private elemental function starts_with_string_string(string, substring) result(match)
Check whether a string starts with substring or not
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value logical
private elemental function starts_with_string_char(string, substring) result(match)
Check whether a string starts with substring or not
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: substring
Return Value logical
private elemental function starts_with_char_string(string, substring) result(match)
Check whether a string starts with substring or not
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value logical
private pure function starts_with_char_char(string, substring) result(match)
Check whether a string starts with substring or not
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: substring
Return Value logical
Call graph
check_starts_with calls starts_with
check_formatter calls starts_with
test_to_string_integer calls check_formatter
test_to_string_logical calls check_formatter
test_to_string_complex calls check_formatter
test_starts_with calls check_starts_with
test_to_string_real calls check_formatter