to_string – Fortran-lang/stdlib
to_string Interface
experimental
76 statements
Source File
public interface to_string
Format or transfer other types as a string. (Specification)
Called by
Contents
Functions
to_string_1_i_int16 to_string_1_i_int32 to_string_1_i_int64 to_string_1_i_int8 to_string_1_l_c_bool to_string_1_l_lk to_string_2_i_int16 to_string_2_i_int32 to_string_2_i_int64 to_string_2_i_int8 to_string_2_l_c_bool to_string_2_l_lk to_string_c_dp to_string_c_sp to_string_r_dp to_string_r_sp
Functions
private pure module function to_string_1_i_int16(value) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: value
Return Value character(len=:),allocatable
private pure module function to_string_1_i_int32(value) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: value
Return Value character(len=:),allocatable
private pure module function to_string_1_i_int64(value) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: value
Return Value character(len=:),allocatable
private pure module function to_string_1_i_int8(value) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: value
Return Value character(len=:),allocatable
private pure module function to_string_1_l_c_bool(value) result(string)
Arguments
Type Intent Optional Attributes Name
logical(kind=c_bool), intent(in) :: value
Return Value character(len=1)
private pure module function to_string_1_l_lk(value) result(string)
Arguments
Type Intent Optional Attributes Name
logical(kind=lk), intent(in) :: value
Return Value character(len=1)
private pure module function to_string_2_i_int16(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_2_i_int32(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_2_i_int64(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_2_i_int8(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_2_l_c_bool(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
logical(kind=c_bool), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_2_l_lk(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
logical(kind=lk), intent(in) :: value
character(len=*), intent(in) :: format
Return Value character(len=:),allocatable
private pure module function to_string_c_dp(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: value
character(len=*), intent(in), optional :: format
Return Value character(len=:),allocatable
private pure module function to_string_c_sp(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: value
character(len=*), intent(in), optional :: format
Return Value character(len=:),allocatable
private pure module function to_string_r_dp(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: value
character(len=*), intent(in), optional :: format
Return Value character(len=:),allocatable
private pure module function to_string_r_sp(value, format) result(string)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: value
character(len=*), intent(in), optional :: format
Return Value character(len=:),allocatable
Call graph
test_insert_at_string_1 calls to_string, compare_list
test_append_prepend_list calls to_string, compare_list
test_to_string_integer calls to_string
test_insert_at_string_3 calls to_string, compare_list
test_to_string_real calls to_string
compare_list calls to_string
test_append_prepend_string calls to_string, compare_list
test_to_string_complex calls to_string
test_append_prepend_array calls to_string, compare_list
check_slicer calls to_string
test_insert_at_list calls to_string, compare_list
test_insert_at_array calls to_string, compare_list
test_to_string_logical calls to_string
test_insert_at_string_2 calls to_string, compare_list
tester calls test_insert_at_string_1, test_insert_at_string_3, test_insert_at_list, test_insert_at_array, test_insert_at_string_2, test_append_prepend_list, test_append_prepend_string, test_append_prepend_array
test_slice_gen calls check_slicer