trace – Fortran-lang/stdlib
trace Interface
12 statements
Source File
public interface trace
Calls
Contents
Module Procedures
trace_rsp trace_rdp trace_rqp trace_csp trace_cdp trace_cqp trace_iint8 trace_iint16 trace_iint32 trace_iint64
Module Procedures
private function trace_rsp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
Return Value real(kind=sp)
private function trace_rdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
Return Value real(kind=dp)
private function trace_rqp(A) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: A(:,:)
Return Value real(kind=qp)
private function trace_csp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: A(:,:)
Return Value complex(kind=sp)
private function trace_cdp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: A(:,:)
Return Value complex(kind=dp)
private function trace_cqp(A) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: A(:,:)
Return Value complex(kind=qp)
private function trace_iint8(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: A(:,:)
Return Value integer(kind=int8)
private function trace_iint16(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: A(:,:)
Return Value integer(kind=int16)
private function trace_iint32(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
Return Value integer(kind=int32)
private function trace_iint64(A) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
Return Value integer(kind=int64)
Call graph
trace calls trace_cdp, trace_cqp, trace_rqp, trace_iint64, trace_rdp, trace_iint32, trace_rsp, trace_iint16, trace_iint8, trace_csp