var – Fortran-lang/stdlib
var Interface
1042 statements
Source File
public interface var
Called by
Contents
Functions
var_1_cdp_cdp var_1_cqp_cqp var_1_csp_csp var_1_iint16_dp var_1_iint32_dp var_1_iint64_dp var_1_iint8_dp var_1_rdp_rdp var_1_rqp_rqp var_1_rsp_rsp var_2_cdp_cdp var_2_cqp_cqp var_2_csp_csp var_2_iint16_dp var_2_iint32_dp var_2_iint64_dp var_2_iint8_dp var_2_rdp_rdp var_2_rqp_rqp var_2_rsp_rsp var_3_cdp_cdp var_3_cqp_cqp var_3_csp_csp var_3_iint16_dp var_3_iint32_dp var_3_iint64_dp var_3_iint8_dp var_3_rdp_rdp var_3_rqp_rqp var_3_rsp_rsp var_4_cdp_cdp var_4_cqp_cqp var_4_csp_csp var_4_iint16_dp var_4_iint32_dp var_4_iint64_dp var_4_iint8_dp var_4_rdp_rdp var_4_rqp_rqp var_4_rsp_rsp var_all_1_cdp_cdp var_all_1_cqp_cqp var_all_1_csp_csp var_all_1_iint16_dp var_all_1_iint32_dp var_all_1_iint64_dp var_all_1_iint8_dp var_all_1_rdp_rdp var_all_1_rqp_rqp var_all_1_rsp_rsp var_all_2_cdp_cdp var_all_2_cqp_cqp var_all_2_csp_csp var_all_2_iint16_dp var_all_2_iint32_dp var_all_2_iint64_dp var_all_2_iint8_dp var_all_2_rdp_rdp var_all_2_rqp_rqp var_all_2_rsp_rsp var_all_3_cdp_cdp var_all_3_cqp_cqp var_all_3_csp_csp var_all_3_iint16_dp var_all_3_iint32_dp var_all_3_iint64_dp var_all_3_iint8_dp var_all_3_rdp_rdp var_all_3_rqp_rqp var_all_3_rsp_rsp var_all_4_cdp_cdp var_all_4_cqp_cqp var_all_4_csp_csp var_all_4_iint16_dp var_all_4_iint32_dp var_all_4_iint64_dp var_all_4_iint8_dp var_all_4_rdp_rdp var_all_4_rqp_rqp var_all_4_rsp_rsp var_mask_1_cdp_cdp var_mask_1_cqp_cqp var_mask_1_csp_csp var_mask_1_iint16_dp var_mask_1_iint32_dp var_mask_1_iint64_dp var_mask_1_iint8_dp var_mask_1_rdp_rdp var_mask_1_rqp_rqp var_mask_1_rsp_rsp var_mask_2_cdp_cdp var_mask_2_cqp_cqp var_mask_2_csp_csp var_mask_2_iint16_dp var_mask_2_iint32_dp var_mask_2_iint64_dp var_mask_2_iint8_dp var_mask_2_rdp_rdp var_mask_2_rqp_rqp var_mask_2_rsp_rsp var_mask_3_cdp_cdp var_mask_3_cqp_cqp var_mask_3_csp_csp var_mask_3_iint16_dp var_mask_3_iint32_dp var_mask_3_iint64_dp var_mask_3_iint8_dp var_mask_3_rdp_rdp var_mask_3_rqp_rqp var_mask_3_rsp_rsp var_mask_4_cdp_cdp var_mask_4_cqp_cqp var_mask_4_csp_csp var_mask_4_iint16_dp var_mask_4_iint32_dp var_mask_4_iint64_dp var_mask_4_iint8_dp var_mask_4_rdp_rdp var_mask_4_rqp_rqp var_mask_4_rsp_rsp var_mask_all_1_cdp_cdp var_mask_all_1_cqp_cqp var_mask_all_1_csp_csp var_mask_all_1_iint16_dp var_mask_all_1_iint32_dp var_mask_all_1_iint64_dp var_mask_all_1_iint8_dp var_mask_all_1_rdp_rdp var_mask_all_1_rqp_rqp var_mask_all_1_rsp_rsp var_mask_all_2_cdp_cdp var_mask_all_2_cqp_cqp var_mask_all_2_csp_csp var_mask_all_2_iint16_dp var_mask_all_2_iint32_dp var_mask_all_2_iint64_dp var_mask_all_2_iint8_dp var_mask_all_2_rdp_rdp var_mask_all_2_rqp_rqp var_mask_all_2_rsp_rsp var_mask_all_3_cdp_cdp var_mask_all_3_cqp_cqp var_mask_all_3_csp_csp var_mask_all_3_iint16_dp var_mask_all_3_iint32_dp var_mask_all_3_iint64_dp var_mask_all_3_iint8_dp var_mask_all_3_rdp_rdp var_mask_all_3_rqp_rqp var_mask_all_3_rsp_rsp var_mask_all_4_cdp_cdp var_mask_all_4_cqp_cqp var_mask_all_4_csp_csp var_mask_all_4_iint16_dp var_mask_all_4_iint32_dp var_mask_all_4_iint64_dp var_mask_all_4_iint8_dp var_mask_all_4_rdp_rdp var_mask_all_4_rqp_rqp var_mask_all_4_rsp_rsp
Functions
public function var_1_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_1_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_1_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_1_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_2_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_2_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_2_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_2_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_3_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_3_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_3_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_3_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_3_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_4_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_4_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_4_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_4_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_4_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_all_1_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_1_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_1_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_1_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_1_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_2_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_2_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_2_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_2_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_2_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_3_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_3_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_3_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_3_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_3_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_4_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_4_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_all_4_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_all_4_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_all_4_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in), optional :: mask
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_1_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_1_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_1_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_1_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_1_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_2_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_2_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_3_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_cdp_cdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_cqp_cqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_csp_csp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_iint16_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_iint32_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_iint64_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_iint8_dp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_rdp_rdp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_rqp_rqp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_4_rsp_rsp(x, dim, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
integer, intent(in) :: dim
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp) (merge(size(x,1),size(x,2),mask=1
public function var_mask_all_1_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_1_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_1_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_1_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_1_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
logical, intent(in) :: mask(:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_2_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_2_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_2_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_2_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_2_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:)
logical, intent(in) :: mask(:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_3_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_3_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_3_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_3_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_3_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:)
logical, intent(in) :: mask(:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_4_cdp_cdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_cqp_cqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_4_csp_csp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
public function var_mask_all_4_iint16_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_iint32_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_iint64_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_iint8_dp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int8), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_rdp_rdp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=dp)
public function var_mask_all_4_rqp_rqp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=qp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=qp)
public function var_mask_all_4_rsp_rsp(x, mask, corrected) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:,:,:,:)
logical, intent(in) :: mask(:,:,:,:)
logical, intent(in), optional :: corrected
Return Value real(kind=sp)
Call graph
cov_mask_1_iint32_dp calls var
cov_mask_1_cdp_cdp calls var
cov_mask_1_iint16_dp calls var
cov_mask_1_cqp_cqp calls var
cov_1_cdp_cdp calls var
cov_1_iint8_dp calls var
cov_mask_1_iint8_dp calls var
cov_1_rdp_rdp calls var
cov_1_csp_csp calls var
cov_1_rqp_rqp calls var
cov_1_rsp_rsp calls var
cov_mask_1_rsp_rsp calls var
cov_1_iint64_dp calls var
cov_mask_1_rdp_rdp calls var
cov_mask_1_iint64_dp calls var
cov_mask_1_csp_csp calls var
cov_1_iint16_dp calls var
cov_1_iint32_dp calls var
cov_mask_1_rqp_rqp calls var
cov_1_cqp_cqp calls var