test_corr – Fortran-lang/stdlib
test_corr Program
118 statements
Source File
Uses
ieee_arithmetic
stdlib_error
stdlib_kinds
stdlib_stats
Calls
Contents
Variables
cd1 d d1 dptol ds sptol
Subroutines
test_cdp test_csp test_dp test_int32 test_int64 test_sp
Variables
Type Attributes Name Initial
complex(kind=dp) :: cd1(5) = [cmplx(0.57706_dp, 0.00000_dp, kind=dp), cmplx(0.00000_dp, 1.44065_dp, kind=dp), cmplx(1.26401_dp, 0.00000_dp, kind=dp), cmplx(0.00000_dp, 0.88833_dp, kind=dp), cmplx(1.14352_dp, 0.00000_dp, kind=dp)]
real(kind=dp) :: d(4,3) = reshape([1._dp, 3._dp, 5._dp, 22._dp, 3._dp, 4._dp, 6._dp, 20._dp, 15._dp, 14._dp, 13._dp, 12._dp], [4, 3])
real(kind=dp) :: d1(5) = [1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp]
real(kind=dp), parameter :: dptol = 1000*epsilon(1._dp)
complex(kind=dp) :: ds(2,3) = reshape([cmplx(1._dp, 0._dp, kind=dp), cmplx(0._dp, 2._dp, kind=dp), cmplx(3._dp, 0._dp, kind=dp), cmplx(0._dp, 4._dp, kind=dp), cmplx(5._dp, 0._dp, kind=dp), cmplx(0._dp, 6._dp, kind=dp)], [2, 3])
real(kind=sp), parameter :: sptol = 1000*epsilon(1._sp)
Subroutines
subroutine test_cdp(x, x2)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
complex(kind=dp), intent(in) :: x2(:,:)
subroutine test_csp(x, x2)
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
complex(kind=sp), intent(in) :: x2(:,:)
subroutine test_dp(x, x2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
real(kind=dp), intent(in) :: x2(:,:)
subroutine test_int32(x, x2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x(:)
integer(kind=int32), intent(in) :: x2(:,:)
subroutine test_int64(x, x2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x(:)
integer(kind=int64), intent(in) :: x2(:,:)
subroutine test_sp(x, x2)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
real(kind=sp), intent(in) :: x2(:,:)
Call graph
test_corr calls test_cdp, test_int64, test_int32, test_dp, test_sp, test_csp
test_cdp calls check, corr
test_int64 calls check, corr
test_int32 calls check, corr
test_dp calls check, corr
test_sp calls check, corr
test_csp calls check, corr
check calls error_stop, optval