test_always_fail – Fortran-lang/stdlib
test_always_fail Program
5 statements
Source File
Uses
stdlib_error
Calls
Contents
None
Call graph
test_always_fail calls check
check calls optval, error_stop