tester – Fortran-lang/stdlib
tester Program
20 statements
Source File
Uses
test_moment
iso_fortran_env
testdrive
Calls
Contents
Variables
fmt is stat testsuites
Variables
Type Attributes Name Initial
character(len=*), parameter :: fmt = '("#", *(1x, a))'
integer :: is
integer :: stat
type(testsuite_type), allocatable :: testsuites(:)
Call graph
tester calls initialize_test_data, new_testsuite, run_testsuite