test_distribution_uniform – Fortran-lang/stdlib
test_distribution_uniform Program
490 statements
Source File
Uses
stdlib_random
stdlib_stats_distribution_uniform
stdlib_error
stdlib_kinds
Calls
Contents
Variables
dptol get put sptol warn
Subroutines
test_shuffle test_uni_cdf_cdp test_uni_cdf_csp test_uni_cdf_iint16 test_uni_cdf_iint32 test_uni_cdf_iint64 test_uni_cdf_iint8 test_uni_cdf_rdp test_uni_cdf_rsp test_uni_pdf_cdp test_uni_pdf_csp test_uni_pdf_iint16 test_uni_pdf_iint32 test_uni_pdf_iint64 test_uni_pdf_iint8 test_uni_pdf_rdp test_uni_pdf_rsp test_uni_rvs_0 test_uni_rvs_cdp test_uni_rvs_csp test_uni_rvs_iint16 test_uni_rvs_iint32 test_uni_rvs_iint64 test_uni_rvs_iint8 test_uni_rvs_rdp test_uni_rvs_rsp
Variables
Type Attributes Name Initial
real(kind=dp), parameter :: dptol = 1000*epsilon(1.0_dp)
integer :: get
integer :: put
real(kind=sp), parameter :: sptol = 1000*epsilon(1.0_sp)
logical :: warn = .true.
Subroutines
subroutine test_shuffle()
Arguments
None
subroutine test_uni_cdf_cdp()
Arguments
None
subroutine test_uni_cdf_csp()
Arguments
None
subroutine test_uni_cdf_iint16()
Arguments
None
subroutine test_uni_cdf_iint32()
Arguments
None
subroutine test_uni_cdf_iint64()
Arguments
None
subroutine test_uni_cdf_iint8()
Arguments
None
subroutine test_uni_cdf_rdp()
Arguments
None
subroutine test_uni_cdf_rsp()
Arguments
None
subroutine test_uni_pdf_cdp()
Arguments
None
subroutine test_uni_pdf_csp()
Arguments
None
subroutine test_uni_pdf_iint16()
Arguments
None
subroutine test_uni_pdf_iint32()
Arguments
None
subroutine test_uni_pdf_iint64()
Arguments
None
subroutine test_uni_pdf_iint8()
Arguments
None
subroutine test_uni_pdf_rdp()
Arguments
None
subroutine test_uni_pdf_rsp()
Arguments
None
subroutine test_uni_rvs_0()
Arguments
None
subroutine test_uni_rvs_cdp()
Arguments
None
subroutine test_uni_rvs_csp()
Arguments
None
subroutine test_uni_rvs_iint16()
Arguments
None
subroutine test_uni_rvs_iint32()
Arguments
None
subroutine test_uni_rvs_iint64()
Arguments
None
subroutine test_uni_rvs_iint8()
Arguments
None
subroutine test_uni_rvs_rdp()
Arguments
None
subroutine test_uni_rvs_rsp()
Arguments
None
Call graph
test_distribution_uniform calls test_uni_cdf_cdp, test_uni_rvs_rsp, test_uni_pdf_iint64, test_uni_pdf_cdp, test_uni_cdf_iint64, test_shuffle, test_uni_pdf_csp, test_uni_rvs_rdp, test_uni_pdf_iint32, test_uni_rvs_iint8, test_uni_rvs_cdp, test_uni_rvs_csp, test_uni_cdf_rsp, test_uni_pdf_rdp, test_uni_rvs_iint16, test_uni_cdf_rdp, test_uni_cdf_iint32, test_uni_cdf_iint16, test_uni_pdf_iint16, test_uni_pdf_rsp, test_uni_cdf_csp, test_uni_rvs_iint64, test_uni_pdf_iint8, test_uni_rvs_iint32, test_uni_cdf_iint8, test_uni_rvs_0
test_uni_cdf_cdp calls uni_cdf, check, uni_rvs
test_uni_rvs_rsp calls check, uni_rvs
test_uni_pdf_iint64 calls check, uni_pdf, uni_rvs
test_uni_pdf_cdp calls check, uni_pdf, uni_rvs
test_uni_cdf_iint64 calls uni_cdf, check, uni_rvs
test_shuffle calls check, shuffle
test_uni_pdf_csp calls check, uni_pdf, uni_rvs
test_uni_rvs_rdp calls check, uni_rvs
test_uni_pdf_iint32 calls check, uni_pdf, uni_rvs
test_uni_rvs_iint8 calls check, uni_rvs
test_uni_rvs_cdp calls check, uni_rvs
test_uni_rvs_csp calls check, uni_rvs
test_uni_cdf_rsp calls uni_cdf, check, uni_rvs
test_uni_pdf_rdp calls check, uni_pdf, uni_rvs
test_uni_rvs_iint16 calls check, uni_rvs
test_uni_cdf_rdp calls uni_cdf, check, uni_rvs
test_uni_cdf_iint32 calls uni_cdf, check, uni_rvs
test_uni_cdf_iint16 calls uni_cdf, check, uni_rvs
test_uni_pdf_iint16 calls check, uni_pdf, uni_rvs
test_uni_pdf_rsp calls check, uni_pdf, uni_rvs
test_uni_cdf_csp calls uni_cdf, check, uni_rvs
test_uni_rvs_iint64 calls check, uni_rvs
test_uni_pdf_iint8 calls check, uni_pdf, uni_rvs
test_uni_rvs_iint32 calls check, uni_rvs
test_uni_cdf_iint8 calls uni_cdf, check, uni_rvs
test_uni_rvs_0 calls check, uni_rvs
check calls error_stop, optval