test_distribution_expon – Fortran-lang/stdlib
test_distribution_expon Program
240 statements
Source File
Uses
stdlib_stats_distribution_exponential
stdlib_error
stdlib_kinds
stdlib_random
Calls
Contents
Variables
dptol get put sptol warn
Subroutines
test_expon_cdf_cdp test_expon_cdf_csp test_expon_cdf_rdp test_expon_cdf_rsp test_expon_pdf_cdp test_expon_pdf_csp test_expon_pdf_rdp test_expon_pdf_rsp test_expon_rvs_cdp test_expon_rvs_csp test_expon_rvs_rdp test_expon_rvs_rsp test_exponential_random_generator
Variables
Type Attributes Name Initial
real(kind=dp), parameter :: dptol = 1000*epsilon(1.0_dp)
integer :: get
integer :: put
real(kind=sp), parameter :: sptol = 1000*epsilon(1.0_sp)
logical :: warn = .true.
Subroutines
subroutine test_expon_cdf_cdp()
Arguments
None
subroutine test_expon_cdf_csp()
Arguments
None
subroutine test_expon_cdf_rdp()
Arguments
None
subroutine test_expon_cdf_rsp()
Arguments
None
subroutine test_expon_pdf_cdp()
Arguments
None
subroutine test_expon_pdf_csp()
Arguments
None
subroutine test_expon_pdf_rdp()
Arguments
None
subroutine test_expon_pdf_rsp()
Arguments
None
subroutine test_expon_rvs_cdp()
Arguments
None
subroutine test_expon_rvs_csp()
Arguments
None
subroutine test_expon_rvs_rdp()
Arguments
None
subroutine test_expon_rvs_rsp()
Arguments
None
subroutine test_exponential_random_generator()
Arguments
None
Call graph
test_distribution_expon calls test_expon_pdf_cdp, test_expon_cdf_rsp, test_expon_rvs_rsp, test_expon_pdf_rsp, test_expon_pdf_rdp, test_expon_pdf_csp, test_expon_rvs_rdp, test_expon_rvs_cdp, test_expon_cdf_csp, test_expon_cdf_rdp, test_exponential_random_generator, test_expon_cdf_cdp, test_expon_rvs_csp
test_expon_pdf_cdp calls pdf_exp, rvs_exp, check
test_expon_cdf_rsp calls rvs_exp, cdf_exp, check
test_expon_rvs_rsp calls rvs_exp, check
test_expon_pdf_rsp calls pdf_exp, rvs_exp, check
test_expon_pdf_rdp calls pdf_exp, rvs_exp, check
test_expon_pdf_csp calls pdf_exp, rvs_exp, check
test_expon_rvs_rdp calls rvs_exp, check
test_expon_rvs_cdp calls rvs_exp, check
test_expon_cdf_csp calls rvs_exp, cdf_exp, check
test_expon_cdf_rdp calls rvs_exp, cdf_exp, check
test_exponential_random_generator calls rvs_exp, check
test_expon_cdf_cdp calls rvs_exp, cdf_exp, check
test_expon_rvs_csp calls rvs_exp, check
check calls optval, error_stop