test_32_bit_hash_performance – Fortran-lang/stdlib
test_32_bit_hash_performance Program
133 statements
Source File
Uses
stdlib_kinds
stdlib_hash_32bit
Program to compare the relative performance of different 32 bit hash functions
Calls
Contents
Variables
block_size huge32 hugep1 index k lun rand rand_object rand_power rand_size repeat test_block test_object test_size
Subroutines
test_fnv_1 test_fnv_1a test_nmhash32 test_nmhash32x test_water
Variables
Type Attributes Name Initial
integer, parameter :: block_size(8) = [1, 2, 4, 8, 16, 64, 256, 1024]
integer(kind=int32), parameter :: huge32 = huge(0_int32)
real(kind=dp), parameter :: hugep1 = real(huge32, dp)+1.0_dp
integer :: index
integer :: k
integer :: lun
real(kind=dp) :: rand(2)
integer(kind=int32) :: rand_object(rand_size)
integer, parameter :: rand_power = 16
integer, parameter :: rand_size = 2**rand_power
integer, parameter :: repeat = 4
integer, parameter :: test_block = 2**10
integer(kind=int8) :: test_object(test_size)
integer, parameter :: test_size = rand_size*4
Subroutines
subroutine test_fnv_1()
Arguments
None
subroutine test_fnv_1a()
Arguments
None
subroutine test_nmhash32()
Arguments
None
subroutine test_nmhash32x()
Arguments
None
subroutine test_water()
Arguments
None
Call graph
test_32_bit_hash_performance calls test_fnv_1a, test_nmhash32x, test_water, test_nmhash32, test_fnv_1
test_fnv_1a calls fnv_1a_hash
test_nmhash32x calls new_nmhash32x_seed, nmhash32x
test_water calls new_water_hash_seed, water_hash
test_nmhash32 calls new_nmhash32_seed, nmhash32
test_fnv_1 calls fnv_1_hash