tester – Fortran-lang/stdlib
tester Program
24 statements
Source File
Uses
testdrive
modchash
iso_fortran_env
iso_c_binding
test_hash_functions
Calls
Contents
Variables
error fmt is stat testsuites
Variables
Type Attributes Name Initial
integer(kind=C_int) :: error
character(len=*), parameter :: fmt = '("#", *(1x, a))'
integer :: is
integer :: stat
type(testsuite_type), allocatable :: testsuites(:)
Call graph
tester calls new_testsuite, run_testsuite, generate_key_array, generate_all_c_hash