test_64_bit_hash_performance – Fortran-lang/stdlib
test_64_bit_hash_performance Program
111 statements
Source File
Uses
stdlib_kinds
stdlib_hash_64bit
Program to compare the relative performance of different 64 bit hash functions
Calls
Contents
Variables
block_size huge32 hugep1 index k lun rand rand_object rand_power rand_size repeat test_object test_size
Subroutines
test_fnv_1 test_fnv_1a test_pengy test_spooky
Variables
Type Attributes Name Initial
integer, parameter :: block_size(8) = [1, 2, 4, 8, 16, 64, 256, 1024]
integer(kind=int32), parameter :: huge32 = huge(0_int32)
real(kind=dp), parameter :: hugep1 = real(huge32, dp)+1.0_dp
integer :: index
integer :: k
integer :: lun
real(kind=dp) :: rand(2)
integer(kind=int32) :: rand_object(rand_size)
integer, parameter :: rand_power = 16
integer, parameter :: rand_size = 2**rand_power
integer, parameter :: repeat = 4
integer(kind=int8) :: test_object(test_size)
integer, parameter :: test_size = rand_size*4
Subroutines
subroutine test_fnv_1()
Arguments
None
subroutine test_fnv_1a()
Arguments
None
subroutine test_pengy()
Arguments
None
subroutine test_spooky()
Arguments
None
Call graph
test_64_bit_hash_performance calls test_pengy, test_fnv_1a, test_spooky, test_fnv_1
test_pengy calls new_pengy_hash_seed, pengy_hash
test_fnv_1a calls fnv_1a_hash
test_spooky calls spooky_hash, new_spooky_hash_seed
test_fnv_1 calls fnv_1_hash