test_distribution_normal – Fortran-lang/stdlib
test_distribution_normal Program
252 statements
Source File
Uses
stdlib_random
stdlib_stats_distribution_uniform
stdlib_stats_distribution_normal
stdlib_error
stdlib_kinds
Calls
Contents
Variables
dptol get put sptol warn
Subroutines
test_nor_cdf_cdp test_nor_cdf_csp test_nor_cdf_rdp test_nor_cdf_rsp test_nor_pdf_cdp test_nor_pdf_csp test_nor_pdf_rdp test_nor_pdf_rsp test_nor_rvs_cdp test_nor_rvs_csp test_nor_rvs_rdp test_nor_rvs_rsp test_normal_random_generator
Variables
Type Attributes Name Initial
real(kind=dp), parameter :: dptol = 1000*epsilon(1.0_dp)
integer :: get
integer :: put
real(kind=sp), parameter :: sptol = 1000*epsilon(1.0_sp)
logical :: warn = .true.
Subroutines
subroutine test_nor_cdf_cdp()
Arguments
None
subroutine test_nor_cdf_csp()
Arguments
None
subroutine test_nor_cdf_rdp()
Arguments
None
subroutine test_nor_cdf_rsp()
Arguments
None
subroutine test_nor_pdf_cdp()
Arguments
None
subroutine test_nor_pdf_csp()
Arguments
None
subroutine test_nor_pdf_rdp()
Arguments
None
subroutine test_nor_pdf_rsp()
Arguments
None
subroutine test_nor_rvs_cdp()
Arguments
None
subroutine test_nor_rvs_csp()
Arguments
None
subroutine test_nor_rvs_rdp()
Arguments
None
subroutine test_nor_rvs_rsp()
Arguments
None
subroutine test_normal_random_generator()
Arguments
None
Call graph
test_distribution_normal calls test_nor_cdf_cdp, test_nor_cdf_csp, test_nor_rvs_rsp, test_nor_pdf_cdp, test_nor_rvs_csp, test_nor_pdf_csp, test_nor_pdf_rdp, test_nor_rvs_cdp, test_nor_pdf_rsp, test_nor_cdf_rdp, test_nor_rvs_rdp, test_normal_random_generator, test_nor_cdf_rsp
test_nor_cdf_cdp calls cdf_normal, rvs_normal, check
test_nor_cdf_csp calls cdf_normal, rvs_normal, check
test_nor_rvs_rsp calls rvs_normal, check
test_nor_pdf_cdp calls pdf_normal, rvs_normal, check
test_nor_rvs_csp calls rvs_normal, check
test_nor_pdf_csp calls pdf_normal, rvs_normal, check
test_nor_pdf_rdp calls pdf_normal, rvs_normal, check
test_nor_rvs_cdp calls rvs_normal, check
test_nor_pdf_rsp calls pdf_normal, rvs_normal, check
test_nor_cdf_rdp calls cdf_normal, rvs_normal, check
test_nor_rvs_rdp calls rvs_normal, check
test_normal_random_generator calls rvs_normal, check
test_nor_cdf_rsp calls cdf_normal, rvs_normal, check
check calls optval, error_stop